-- =============================================================================
-- Converter Input for: ODS_GRDN_AEP_OBSER_THE_OBSRVR_CORE_VISIT
-- =============================================================================

$TYPE: INSERT;

$TARGET_TABLE: DATAWAREHOUSE.PUBLIC.ODS_GRDN_AEP_OBSER_THE_OBSRVR_CORE_VISIT;

$TARGET_TABLE_COLUMNS:
TEMPLTTITLE_TX, TITLE_TX, DESCN_TX, OBSRVRFORMATTED_NM, OBSRVRUSER_NM, OBSRVRFRST_NM, OBSRVRMDL_NM, OBSRVRLAST_NM, OBSRVREMAIL_TX, ORIGIN_TX, TMZ_NM, CREATDUSER_NM, CREATD_DTM, MODFD_DTM, STAT_TX, BSNS_UNIT_NM, CITY_NM, STATE_NM, COREVISITLOC_TX, COREVISITDESCN_TX, PEOPLEOBSRVD_TX, OBSRVRINTRODSELF_TX, DATETIME_DTM, WORKPROCOBSRVD_TX, OBS_HIERARCHY_1_TX, OBS_HIERARCHY_2_TX, OBS_HIERARCHY_3_TX, OBS_HIERARCHY_4_TX, OBS_HIERARCHY_5_TX, OBS_HIERARCHY_6_TX, OBS_HIERARCHY_7_TX, OBS_HIERARCHY_8_TX, OBS_HIERARCHY_9_TX, OBS_HIERARCHY_10_TX, OBS_HIERARCHY_11_TX, OBS_HIERARCHY_12_TX, OBS_HIERARCHY_13_TX, OBS_HIERARCHY_14_TX, OBS_HIERARCHY_15_TX, OBS_HIERARCHY_16_TX, OBS_HIERARCHY_17_TX, OBS_HIERARCHY_18_TX, OBS_HIERARCHY_19_TX, OBS_HIERARCHY_20_TX, OBS_HIERARCHY_21_TX, OBS_HIERARCHY_22_TX, OBS_HIERARCHY_23_TX, OBS_HIERARCHY_24_TX, OBSGOTPERATTN_TX, OBSENGANDCOACHED_TX, OBSTHANKEDEMP_TX, OBSSTOPPEDJOB_TX, PEERSPRESTOINTERVENUE_TX, PEERSCOACHEDONRES_TX, CMNT_TX, TMPLTCTGY_TX, OBSRVTN_NB, EDW_LAST_UPDT_DTM, EDW_LAST_UPDT_NM;

$PRIMARY_KEY: OBSRVTN_NB;

$SPLIT_CTE: exp_ODS_OBSER_THE_OBSRVR;

$DESC_TABLE:
name	type	kind	null?	default
OBSRVTN_NB	VARCHAR(15)	COLUMN	N	
DATETIME_DTM	TIMESTAMP_NTZ(9)	COLUMN	N	
TEMPLTTITLE_TX	VARCHAR(255)	COLUMN	Y	
TITLE_TX	VARCHAR(255)	COLUMN	Y	
DESCN_TX	VARCHAR(4000)	COLUMN	Y	
OBSRVRFORMATTED_NM	VARCHAR(150)	COLUMN	Y	
OBSRVRUSER_NM	VARCHAR(150)	COLUMN	Y	
OBSRVRFRST_NM	VARCHAR(150)	COLUMN	Y	
OBSRVRMDL_NM	VARCHAR(150)	COLUMN	Y	
OBSRVRLAST_NM	VARCHAR(150)	COLUMN	Y	
OBSRVREMAIL_TX	VARCHAR(255)	COLUMN	Y	
ORIGIN_TX	VARCHAR(255)	COLUMN	Y	
TMZ_NM	VARCHAR(20)	COLUMN	Y	
CREATDUSER_NM	VARCHAR(150)	COLUMN	Y	
CREATD_DTM	VARCHAR(150)	COLUMN	Y	
MODFD_DTM	VARCHAR(150)	COLUMN	Y	
STAT_TX	VARCHAR(100)	COLUMN	Y	
BSNS_UNIT_NM	VARCHAR(150)	COLUMN	Y	
CITY_NM	VARCHAR(150)	COLUMN	Y	
STATE_NM	VARCHAR(150)	COLUMN	Y	
COREVISITLOC_TX	VARCHAR(150)	COLUMN	Y	
COREVISITDESCN_TX	VARCHAR(4000)	COLUMN	Y	
PEOPLEOBSRVD_TX	VARCHAR(4000)	COLUMN	Y	
OBSRVRINTRODSELF_TX	VARCHAR(150)	COLUMN	Y	
WORKPROCOBSRVD_TX	VARCHAR(150)	COLUMN	Y	
OBSGOTPERATTN_TX	VARCHAR(150)	COLUMN	Y	
OBSENGANDCOACHED_TX	VARCHAR(150)	COLUMN	Y	
OBSTHANKEDEMP_TX	VARCHAR(150)	COLUMN	Y	
OBSSTOPPEDJOB_TX	VARCHAR(150)	COLUMN	Y	
PEERSPRESTOINTERVENUE_TX	VARCHAR(150)	COLUMN	Y	
PEERSCOACHEDONRES_TX	VARCHAR(150)	COLUMN	Y	
CMNT_TX	VARCHAR(255)	COLUMN	Y	
TMPLTCTGY_TX	VARCHAR(255)	COLUMN	Y	
EDW_LAST_UPDT_NM	VARCHAR(50)	COLUMN	Y	
EDW_LAST_UPDT_DTM	TIMESTAMP_NTZ(9)	COLUMN	Y	
OBS_HIERARCHY_1_TX	VARCHAR(255)	COLUMN	Y	
OBS_HIERARCHY_2_TX	VARCHAR(255)	COLUMN	Y	
OBS_HIERARCHY_3_TX	VARCHAR(255)	COLUMN	Y	
OBS_HIERARCHY_4_TX	VARCHAR(255)	COLUMN	Y	
OBS_HIERARCHY_5_TX	VARCHAR(255)	COLUMN	Y	
OBS_HIERARCHY_6_TX	VARCHAR(255)	COLUMN	Y	
OBS_HIERARCHY_7_TX	VARCHAR(255)	COLUMN	Y	
OBS_HIERARCHY_8_TX	VARCHAR(255)	COLUMN	Y	
OBS_HIERARCHY_9_TX	VARCHAR(255)	COLUMN	Y	
OBS_HIERARCHY_10_TX	VARCHAR(255)	COLUMN	Y	
OBS_HIERARCHY_11_TX	VARCHAR(255)	COLUMN	Y	
OBS_HIERARCHY_12_TX	VARCHAR(255)	COLUMN	Y	
OBS_HIERARCHY_13_TX	VARCHAR(255)	COLUMN	Y	
OBS_HIERARCHY_14_TX	VARCHAR(255)	COLUMN	Y	
OBS_HIERARCHY_15_TX	VARCHAR(255)	COLUMN	Y	
OBS_HIERARCHY_16_TX	VARCHAR(255)	COLUMN	Y	
OBS_HIERARCHY_17_TX	VARCHAR(255)	COLUMN	Y	
OBS_HIERARCHY_18_TX	VARCHAR(255)	COLUMN	Y	
OBS_HIERARCHY_19_TX	VARCHAR(255)	COLUMN	Y	
OBS_HIERARCHY_20_TX	VARCHAR(255)	COLUMN	Y	
OBS_HIERARCHY_21_TX	VARCHAR(255)	COLUMN	Y	
OBS_HIERARCHY_22_TX	VARCHAR(255)	COLUMN	Y	
OBS_HIERARCHY_23_TX	VARCHAR(255)	COLUMN	Y	
OBS_HIERARCHY_24_TX	VARCHAR(255)	COLUMN	Y;

$UPDATE_COLUMNS: NONE;

$AUTOSYS_JOB_NAME: GRDN_AEP_OBSER_THE_OBSRVR_CORE_VISIT_LOAD;

$SOURCE_CODE:
WITH
SQ_STG_GRDN_OBSER_THE_OBSER_COREVISIT AS (
  SELECT DISTINCT A.OBS_NUMBER, A.OBS_DATETIME, A.OBS_TEMPLATETITLE, A.OBS_TITLE, A.OBS_DESCRIPTION, A.OBS_OBSERVERFORMATTEDNAME, A.OBS_OBSERVERUSERNAME, A.OBS_OBSERVERFIRSTNAME, A.OBS_OBSERVERMIDDLENAME, A.OBS_OBSERVERLASTNAME, A.OBS_OBSERVEREMAIL, A.OBS_ORIGIN, A.OBS_TIMEZONE, A.OBS_CREATEDUSER, A.OBS_CREATEDDATETIME, A.OBS_MODIFIEDDATETIME, A.OBS_STATUS, A.BUSINESS_UNIT, A.CITY, A.STATE, A.COREVISITLOCATION, A.COREVISITDESCRIPTION, A.PEOPLEOBSERVED, A.OBSERVERINTRODUCEDSELF, A.OBS_HIERARCHYFIELD1, A.OBS_HIERARCHYFIELD2, A.OBS_HIERARCHYFIELD3, A.OBS_HIERARCHYFIELD4, A.OBS_HIERARCHYFIELD5, A.OBS_HIERARCHYFIELD6, A.OBS_HIERARCHYFIELD7, A.OBS_HIERARCHYFIELD8, A.OBS_HIERARCHYFIELD9, A.OBS_HIERARCHYFIELD10, A.OBS_HIERARCHYFIELD11, A.OBS_HIERARCHYFIELD12, A.OBS_HIERARCHYFIELD13, A.OBS_HIERARCHYFIELD14, A.OBS_HIERARCHYFIELD15, A.OBS_HIERARCHYFIELD16, A.OBS_HIERARCHYFIELD17, A.OBS_HIERARCHYFIELD18, A.OBS_HIERARCHYFIELD19, A.OBS_HIERARCHYFIELD20, A.OBS_HIERARCHYFIELD21, A.OBS_HIERARCHYFIELD22, A.OBS_HIERARCHYFIELD23, A.OBS_HIERARCHYFIELD24, A.WORKPROCESSOBSERVED, A.OBSGOTPERATTN, A.OBSENGANDCOACHED, A.OBSTHANKEDEMP, A.OBSSTOPPEDJOB, A.PEERSPRESTOINTERVENUE, A.PEERSCOACHEDONRES, A.COMMENTS, A.OBS_TEMPLATECATEGORY FROM SHMSADM.STG_GRDN_OBSER_THE_OBSER_COREVISIT A, (select obs_number, max(OBS_MODIFIEDDATETIME) OBS_MODIFIEDDATETIME from SHMSADM.STG_GRDN_OBSER_THE_OBSER_COREVISIT group by obs_number) B where A.OBS_NUMBER=B.OBS_NUMBER and A.OBS_MODIFIEDDATETIME=B.OBS_MODIFIEDDATETIME
),

exp_ODS_OBSER_THE_OBSRVR AS (
  SELECT
    SQ_STG_GRDN_OBSER_THE_OBSER_COREVISIT.* EXCLUDE (OUT_ODS_DATETIME, UPD_DT, USER_NM),
    TRY_TO_DATE(OBS_DATETIME, 'YYYY-MM-DD HH24:MI:SS') AS out_ODS_DATETIME,
    'SHMSUSER' AS USER_NM,
    CURRENT_TIMESTAMP() AS UPD_DT
  FROM SQ_STG_GRDN_OBSER_THE_OBSER_COREVISIT
)

INSERT INTO ODS_GRDN_AEP_OBSER_THE_OBSRVR_CORE_VISIT (
  TEMPLTTITLE_TX, TITLE_TX, DESCN_TX, OBSRVRFORMATTED_NM, OBSRVRUSER_NM, OBSRVRFRST_NM, OBSRVRMDL_NM, OBSRVRLAST_NM, OBSRVREMAIL_TX, ORIGIN_TX, TMZ_NM, CREATDUSER_NM, CREATD_DTM, MODFD_DTM, STAT_TX, BSNS_UNIT_NM, CITY_NM, STATE_NM, COREVISITLOC_TX, COREVISITDESCN_TX, PEOPLEOBSRVD_TX, OBSRVRINTRODSELF_TX, DATETIME_DTM, WORKPROCOBSRVD_TX, OBS_HIERARCHY_1_TX, OBS_HIERARCHY_2_TX, OBS_HIERARCHY_3_TX, OBS_HIERARCHY_4_TX, OBS_HIERARCHY_5_TX, OBS_HIERARCHY_6_TX, OBS_HIERARCHY_7_TX, OBS_HIERARCHY_8_TX, OBS_HIERARCHY_9_TX, OBS_HIERARCHY_10_TX, OBS_HIERARCHY_11_TX, OBS_HIERARCHY_12_TX, OBS_HIERARCHY_13_TX, OBS_HIERARCHY_14_TX, OBS_HIERARCHY_15_TX, OBS_HIERARCHY_16_TX, OBS_HIERARCHY_17_TX, OBS_HIERARCHY_18_TX, OBS_HIERARCHY_19_TX, OBS_HIERARCHY_20_TX, OBS_HIERARCHY_21_TX, OBS_HIERARCHY_22_TX, OBS_HIERARCHY_23_TX, OBS_HIERARCHY_24_TX, OBSGOTPERATTN_TX, OBSENGANDCOACHED_TX, OBSTHANKEDEMP_TX, OBSSTOPPEDJOB_TX, PEERSPRESTOINTERVENUE_TX, PEERSCOACHEDONRES_TX, CMNT_TX, TMPLTCTGY_TX, OBSRVTN_NB, EDW_LAST_UPDT_DTM, EDW_LAST_UPDT_NM
)
SELECT
  OBS_TEMPLATETITLE, OBS_TITLE, OBS_DESCRIPTION, OBS_OBSERVERFORMATTEDNAME, OBS_OBSERVERUSERNAME, OBS_OBSERVERFIRSTNAME, OBS_OBSERVERMIDDLENAME, OBS_OBSERVERLASTNAME, OBS_OBSERVEREMAIL, OBS_ORIGIN, OBS_TIMEZONE, OBS_CREATEDUSER, OBS_CREATEDDATETIME, OBS_MODIFIEDDATETIME, OBS_STATUS, BUSINESS_UNIT, CITY, STATE, COREVISITLOCATION, COREVISITDESCRIPTION, PEOPLEOBSERVED, OBSERVERINTRODUCEDSELF, out_ODS_DATETIME, WORKPROCESSOBSERVED, OBS_HIERARCHYFIELD1, OBS_HIERARCHYFIELD2, OBS_HIERARCHYFIELD3, OBS_HIERARCHYFIELD4, OBS_HIERARCHYFIELD5, OBS_HIERARCHYFIELD6, OBS_HIERARCHYFIELD7, OBS_HIERARCHYFIELD8, OBS_HIERARCHYFIELD9, OBS_HIERARCHYFIELD10, OBS_HIERARCHYFIELD11, OBS_HIERARCHYFIELD12, OBS_HIERARCHYFIELD13, OBS_HIERARCHYFIELD14, OBS_HIERARCHYFIELD15, OBS_HIERARCHYFIELD16, OBS_HIERARCHYFIELD17, OBS_HIERARCHYFIELD18, OBS_HIERARCHYFIELD19, OBS_HIERARCHYFIELD20, OBS_HIERARCHYFIELD21, OBS_HIERARCHYFIELD22, OBS_HIERARCHYFIELD23, OBS_HIERARCHYFIELD24, OBSGOTPERATTN, OBSENGANDCOACHED, OBSTHANKEDEMP, OBSSTOPPEDJOB, PEERSPRESTOINTERVENUE, PEERSCOACHEDONRES, COMMENTS, OBS_TEMPLATECATEGORY, OBSRVTN_NB, UPD_DT, USER_NM
FROM exp_ODS_OBSER_THE_OBSRVR;
