-- Diagnostics for SHEMS_BDY_PRT_DIM source row mismatch.
-- Run these in Snowflake before dbt to confirm whether the source join can reproduce the backup rows.

SELECT 'A bridge rows' AS CHECK_NAME, COUNT(*) AS ROW_COUNT
FROM CRPDB01_DEV_SANDBOX.SHMSADM.ODS_SHMS_INCDNT_OII_BDYPRT;

SELECT 'B body part rows' AS CHECK_NAME, COUNT(*) AS ROW_COUNT
FROM CRPDB01_DEV_SANDBOX.SHMSADM.ODS_SHMS_INCDNT_BDY_PRT;

SELECT 'C incident rows' AS CHECK_NAME, COUNT(*) AS ROW_COUNT
FROM CRPDB01_DEV_SANDBOX.SHMSADM.ODS_SHMS_INCDNT;

SELECT 'A rows with natural keys' AS CHECK_NAME, COUNT(*) AS ROW_COUNT
FROM CRPDB01_DEV_SANDBOX.SHMSADM.ODS_SHMS_INCDNT_OII_BDYPRT A
WHERE A.BPIN_ID IS NOT NULL
  AND A.INJRY_ILLNSS_ID IS NOT NULL;

SELECT 'A to B matched rows' AS CHECK_NAME, COUNT(*) AS ROW_COUNT
FROM CRPDB01_DEV_SANDBOX.SHMSADM.ODS_SHMS_INCDNT_OII_BDYPRT A
JOIN CRPDB01_DEV_SANDBOX.SHMSADM.ODS_SHMS_INCDNT_BDY_PRT B
  ON A.BPIN_ID = B.BDY_PRT_ID
WHERE A.INJRY_ILLNSS_ID IS NOT NULL;

SELECT 'A to B unmatched rows' AS CHECK_NAME, COUNT(*) AS ROW_COUNT
FROM CRPDB01_DEV_SANDBOX.SHMSADM.ODS_SHMS_INCDNT_OII_BDYPRT A
LEFT JOIN CRPDB01_DEV_SANDBOX.SHMSADM.ODS_SHMS_INCDNT_BDY_PRT B
  ON A.BPIN_ID = B.BDY_PRT_ID
WHERE A.BPIN_ID IS NOT NULL
  AND A.INJRY_ILLNSS_ID IS NOT NULL
  AND B.BDY_PRT_ID IS NULL;

SELECT
  A.BPIN_ID,
  A.INJRY_ILLNSS_ID,
  B.BDY_PRT_ID,
  B.RECORD_NB,
  B.BDY_PRT_NM,
  B.INJ_NTR_TX
FROM CRPDB01_DEV_SANDBOX.SHMSADM.ODS_SHMS_INCDNT_OII_BDYPRT A
LEFT JOIN CRPDB01_DEV_SANDBOX.SHMSADM.ODS_SHMS_INCDNT_BDY_PRT B
  ON A.BPIN_ID = B.BDY_PRT_ID
WHERE A.BPIN_ID IS NOT NULL
  AND A.INJRY_ILLNSS_ID IS NOT NULL
ORDER BY B.BDY_PRT_ID NULLS FIRST
LIMIT 20;
