-- =============================================================================
-- Mapping: m_shems_bdy_prt_dim_ins_upd
-- Source: Informatica converted to SQL
-- Converter input for sql_to_dbt_converter_v38.py
-- =============================================================================

$TYPE: INSERT, UPDATE;

$TARGET_TABLE: CRPDB01_DEV_SANDBOX.SHMSADM.SHEMS_BDY_PRT_DIM;

$TARGET_TABLE_COLUMNS: BDY_PRT_KEY, BDY_PRT_ID, INJRY_ILLNSS_ID, CREATED_DT, MODIFIED_DT, RECORD_NM, RECORD_NB, BDY_PRT_NM, INJ_NTR_TX, EFFCT_STRT_DT, EFFCT_END_DT, ACTIVE_FLAG, EDW_LAST_UPDT_USER_ID, EDW_LAST_UPDT_TS, HIGH_ENRGY_HZRD_TX, INJRY_SUSTAIN_1_TX, INJRY_SUSTAIN_2_TX, BDY_PRT_GRP_TX;

$PRIMARY_KEY: BDY_PRT_KEY;

$UPDATE_COLUMNS:
TGT.EFFCT_END_DT = SRC.EFFCT_END_DT,
TGT.ACTIVE_FLAG = SRC.ACTIVE_FLAG,
TGT.EDW_LAST_UPDT_USER_ID = SRC.EDW_LAST_UPDT_USER_ID,
TGT.EDW_LAST_UPDT_TS = SRC.EDW_LAST_UPDT_TS;

$SPLIT_CTE: FINAL_ROWS;

$AUTOSYS_JOB_NAME: S_M_SHEMS_BDY_PRT;

$SOURCE_CODE:
WITH SQ_ODS_SHMS_INCDNT_BDY_PRT AS (
  SELECT
    B.BDY_PRT_ID AS BDY_PRT_ID,
    A.INJRY_ILLNSS_ID AS INJRY_ILLNSS_ID,
    B.CREATED_DT AS CREATED_DT,
    B.MODIFIED_DT AS MODIFIED_DT,
    B.RECORD_NM AS RECORD_NM,
    B.RECORD_NB AS RECORD_NB,
    B.BDY_PRT_NM AS BDY_PRT_NM,
    B.INJ_NTR_TX AS INJ_NTR_TX,
    C.HIGH_ENRGY_HZRD_TX AS HIGH_ENRGY_HZRD_TX,
    C.INJRY_SUSTAIN_1_TX AS INJRY_SUSTAIN_1_TX,
    C.INJRY_SUSTAIN_2_TX AS INJRY_SUSTAIN_2_TX,
    C.BDY_PRT_GRP_TX AS BDY_PRT_GRP_TX
  FROM CRPDB01_DEV_SANDBOX.SHMSADM.ODS_SHMS_INCDNT_OII_BDYPRT A
  LEFT JOIN CRPDB01_DEV_SANDBOX.SHMSADM.ODS_SHMS_INCDNT_BDY_PRT B
    ON A.BPIN_ID = B.BDY_PRT_ID
  LEFT JOIN CRPDB01_DEV_SANDBOX.SHMSADM.ODS_SHMS_INCDNT C
    ON A.INJRY_ILLNSS_ID = C.INCDNT_ID
),
CURRENT_DIM AS (
  SELECT
    DIM.BDY_PRT_KEY,
    DIM.BDY_PRT_ID,
    DIM.INJRY_ILLNSS_ID,
    DIM.CREATED_DT,
    DIM.MODIFIED_DT,
    DIM.RECORD_NM,
    DIM.RECORD_NB,
    DIM.BDY_PRT_NM,
    DIM.INJ_NTR_TX,
    DIM.EFFCT_STRT_DT,
    DIM.EFFCT_END_DT,
    DIM.ACTIVE_FLAG,
    DIM.HIGH_ENRGY_HZRD_TX,
    DIM.INJRY_SUSTAIN_1_TX,
    DIM.INJRY_SUSTAIN_2_TX,
    DIM.BDY_PRT_GRP_TX
  FROM CRPDB01_DEV_SANDBOX.SHMSADM.SHEMS_BDY_PRT_DIM DIM
  WHERE DIM.ACTIVE_FLAG = 'Y'
),
EXPTRANS_step1 AS (
  SELECT
    SRC.BDY_PRT_ID,
    SRC.INJRY_ILLNSS_ID,
    SRC.CREATED_DT,
    SRC.MODIFIED_DT,
    SRC.RECORD_NM,
    SRC.RECORD_NB,
    SRC.BDY_PRT_NM,
    SRC.INJ_NTR_TX,
    SRC.HIGH_ENRGY_HZRD_TX,
    SRC.INJRY_SUSTAIN_1_TX,
    SRC.INJRY_SUSTAIN_2_TX,
    SRC.BDY_PRT_GRP_TX,
    DIM.BDY_PRT_KEY AS LKP_BDY_PRT_KEY,
    DIM.BDY_PRT_ID AS LKP_BDY_PRT_ID,
    DIM.INJRY_ILLNSS_ID AS LKP_INJRY_ILLNSS_ID,
    MD5(
      COALESCE(CAST(IFF(SRC.CREATED_DT IS NULL, '', TO_VARCHAR(SRC.CREATED_DT, 'MMDDYYYY')) AS VARCHAR), '') ||
      COALESCE(CAST(IFF(SRC.MODIFIED_DT IS NULL, '', TO_VARCHAR(SRC.MODIFIED_DT, 'MMDDYYYY')) AS VARCHAR), '') ||
      COALESCE(CAST(IFF(SRC.RECORD_NM IS NULL, '', SRC.RECORD_NM) AS VARCHAR), '') ||
      COALESCE(CAST(IFF(SRC.RECORD_NB IS NULL, '0', SRC.RECORD_NB) AS VARCHAR), '') ||
      COALESCE(CAST(IFF(SRC.BDY_PRT_NM IS NULL, '', SRC.BDY_PRT_NM) AS VARCHAR), '') ||
      COALESCE(CAST(IFF(SRC.INJ_NTR_TX IS NULL, '', SRC.INJ_NTR_TX) AS VARCHAR), '') ||
      COALESCE(CAST(IFF(SRC.HIGH_ENRGY_HZRD_TX IS NULL, '', SRC.HIGH_ENRGY_HZRD_TX) AS VARCHAR), '') ||
      COALESCE(CAST(IFF(SRC.INJRY_SUSTAIN_1_TX IS NULL, '', SRC.INJRY_SUSTAIN_1_TX) AS VARCHAR), '') ||
      COALESCE(CAST(IFF(SRC.INJRY_SUSTAIN_2_TX IS NULL, '', SRC.INJRY_SUSTAIN_2_TX) AS VARCHAR), '') ||
      COALESCE(CAST(IFF(SRC.BDY_PRT_GRP_TX IS NULL, '', SRC.BDY_PRT_GRP_TX) AS VARCHAR), '')
    ) AS SRC_CHECKSUM,
    MD5(
      COALESCE(CAST(IFF(DIM.CREATED_DT IS NULL, '', TO_VARCHAR(DIM.CREATED_DT, 'MMDDYYYY')) AS VARCHAR), '') ||
      COALESCE(CAST(IFF(DIM.MODIFIED_DT IS NULL, '', TO_VARCHAR(DIM.MODIFIED_DT, 'MMDDYYYY')) AS VARCHAR), '') ||
      COALESCE(CAST(IFF(DIM.RECORD_NM IS NULL, '', DIM.RECORD_NM) AS VARCHAR), '') ||
      COALESCE(CAST(IFF(DIM.RECORD_NB IS NULL, '0', DIM.RECORD_NB) AS VARCHAR), '') ||
      COALESCE(CAST(IFF(DIM.BDY_PRT_NM IS NULL, '', DIM.BDY_PRT_NM) AS VARCHAR), '') ||
      COALESCE(CAST(IFF(DIM.INJ_NTR_TX IS NULL, '', DIM.INJ_NTR_TX) AS VARCHAR), '') ||
      COALESCE(CAST(IFF(DIM.HIGH_ENRGY_HZRD_TX IS NULL, '', DIM.HIGH_ENRGY_HZRD_TX) AS VARCHAR), '') ||
      COALESCE(CAST(IFF(DIM.INJRY_SUSTAIN_1_TX IS NULL, '', DIM.INJRY_SUSTAIN_1_TX) AS VARCHAR), '') ||
      COALESCE(CAST(IFF(DIM.INJRY_SUSTAIN_2_TX IS NULL, '', DIM.INJRY_SUSTAIN_2_TX) AS VARCHAR), '') ||
      COALESCE(CAST(IFF(DIM.BDY_PRT_GRP_TX IS NULL, '', DIM.BDY_PRT_GRP_TX) AS VARCHAR), '')
    ) AS LKP_CHECKSUM
  FROM SQ_ODS_SHMS_INCDNT_BDY_PRT SRC
  LEFT JOIN CURRENT_DIM DIM
    ON DIM.BDY_PRT_ID = SRC.BDY_PRT_ID
   AND DIM.INJRY_ILLNSS_ID = SRC.INJRY_ILLNSS_ID
),
EXPTRANS AS (
  SELECT
    EXPTRANS_step1.*,
    IFF(
      LKP_BDY_PRT_ID IS NULL OR LKP_INJRY_ILLNSS_ID IS NULL,
      'I',
      IFF(SRC_CHECKSUM <> LKP_CHECKSUM, 'U', NULL)
    ) AS FLAG
  FROM EXPTRANS_step1
),
RTRTRANS_INSERT_ONLY AS (
  SELECT
    BDY_PRT_ID,
    INJRY_ILLNSS_ID,
    CREATED_DT,
    MODIFIED_DT,
    RECORD_NM,
    RECORD_NB,
    BDY_PRT_NM,
    INJ_NTR_TX,
    HIGH_ENRGY_HZRD_TX,
    INJRY_SUSTAIN_1_TX,
    INJRY_SUSTAIN_2_TX,
    BDY_PRT_GRP_TX,
    CURRENT_TIMESTAMP() AS EFFCT_STRT_DT,
    TRY_TO_DATE('12-31-9999', 'MM-DD-YYYY') AS EFFCT_END_DT,
    'Y' AS ACTIVE_FLAG,
    'SHMSUSER' AS EDW_LAST_UPDT_USER_ID,
    CURRENT_TIMESTAMP() AS EDW_LAST_UPDT_TS
  FROM EXPTRANS
  WHERE FLAG = 'I'
    AND BDY_PRT_ID IS NOT NULL
    AND INJRY_ILLNSS_ID IS NOT NULL
    AND RECORD_NB IS NOT NULL
),
RTRTRANS_INSERT_UPDATE AS (
  SELECT
    LKP_BDY_PRT_KEY,
    BDY_PRT_ID,
    INJRY_ILLNSS_ID,
    CREATED_DT,
    MODIFIED_DT,
    RECORD_NM,
    RECORD_NB,
    BDY_PRT_NM,
    INJ_NTR_TX,
    HIGH_ENRGY_HZRD_TX,
    INJRY_SUSTAIN_1_TX,
    INJRY_SUSTAIN_2_TX,
    BDY_PRT_GRP_TX,
    CURRENT_TIMESTAMP() AS EFFCT_STRT_DT,
    TRY_TO_DATE('12-31-9999', 'MM-DD-YYYY') AS EFFCT_END_DT,
    'Y' AS ACTIVE_FLAG,
    'SHMSUSER' AS EDW_LAST_UPDT_USER_ID,
    CURRENT_TIMESTAMP() AS EDW_LAST_UPDT_TS
  FROM EXPTRANS
  WHERE FLAG = 'U'
    AND BDY_PRT_ID IS NOT NULL
    AND INJRY_ILLNSS_ID IS NOT NULL
    AND RECORD_NB IS NOT NULL
),
EXISTING_ROWS_TO_EXPIRE AS (
  SELECT
    LKP_BDY_PRT_KEY AS BDY_PRT_KEY,
    BDY_PRT_ID,
    INJRY_ILLNSS_ID,
    CREATED_DT,
    MODIFIED_DT,
    RECORD_NM,
    RECORD_NB,
    BDY_PRT_NM,
    INJ_NTR_TX,
    CURRENT_TIMESTAMP() AS EFFCT_STRT_DT,
    CURRENT_TIMESTAMP() AS EFFCT_END_DT,
    'N' AS ACTIVE_FLAG,
    'SHMSUSER' AS EDW_LAST_UPDT_USER_ID,
    CURRENT_TIMESTAMP() AS EDW_LAST_UPDT_TS,
    HIGH_ENRGY_HZRD_TX,
    INJRY_SUSTAIN_1_TX,
    INJRY_SUSTAIN_2_TX,
    BDY_PRT_GRP_TX
  FROM RTRTRANS_INSERT_UPDATE
),
NEW_ACTIVE_ROWS AS (
  SELECT
    COALESCE((SELECT MAX(BDY_PRT_KEY::NUMBER) FROM CRPDB01_DEV_SANDBOX.SHMSADM.SHEMS_BDY_PRT_DIM), 0)
      + ROW_NUMBER() OVER (ORDER BY BDY_PRT_ID, INJRY_ILLNSS_ID) AS BDY_PRT_KEY,
    BDY_PRT_ID,
    INJRY_ILLNSS_ID,
    CREATED_DT,
    MODIFIED_DT,
    RECORD_NM,
    RECORD_NB,
    BDY_PRT_NM,
    INJ_NTR_TX,
    EFFCT_STRT_DT,
    EFFCT_END_DT,
    ACTIVE_FLAG,
    EDW_LAST_UPDT_USER_ID,
    EDW_LAST_UPDT_TS,
    HIGH_ENRGY_HZRD_TX,
    INJRY_SUSTAIN_1_TX,
    INJRY_SUSTAIN_2_TX,
    BDY_PRT_GRP_TX
  FROM RTRTRANS_INSERT_ONLY
  UNION ALL
  SELECT
    COALESCE((SELECT MAX(BDY_PRT_KEY::NUMBER) FROM CRPDB01_DEV_SANDBOX.SHMSADM.SHEMS_BDY_PRT_DIM), 0)
      + (SELECT COUNT(*) FROM RTRTRANS_INSERT_ONLY)
      + ROW_NUMBER() OVER (ORDER BY BDY_PRT_ID, INJRY_ILLNSS_ID) AS BDY_PRT_KEY,
    BDY_PRT_ID,
    INJRY_ILLNSS_ID,
    CREATED_DT,
    MODIFIED_DT,
    RECORD_NM,
    RECORD_NB,
    BDY_PRT_NM,
    INJ_NTR_TX,
    EFFCT_STRT_DT,
    EFFCT_END_DT,
    ACTIVE_FLAG,
    EDW_LAST_UPDT_USER_ID,
    EDW_LAST_UPDT_TS,
    HIGH_ENRGY_HZRD_TX,
    INJRY_SUSTAIN_1_TX,
    INJRY_SUSTAIN_2_TX,
    BDY_PRT_GRP_TX
  FROM RTRTRANS_INSERT_UPDATE
),
FINAL_ROWS AS (
  SELECT
    BDY_PRT_KEY,
    BDY_PRT_ID,
    INJRY_ILLNSS_ID,
    CREATED_DT,
    MODIFIED_DT,
    RECORD_NM,
    RECORD_NB,
    BDY_PRT_NM,
    INJ_NTR_TX,
    EFFCT_STRT_DT,
    EFFCT_END_DT,
    ACTIVE_FLAG,
    EDW_LAST_UPDT_USER_ID,
    EDW_LAST_UPDT_TS,
    HIGH_ENRGY_HZRD_TX,
    INJRY_SUSTAIN_1_TX,
    INJRY_SUSTAIN_2_TX,
    BDY_PRT_GRP_TX
  FROM EXISTING_ROWS_TO_EXPIRE
  UNION ALL
  SELECT
    BDY_PRT_KEY,
    BDY_PRT_ID,
    INJRY_ILLNSS_ID,
    CREATED_DT,
    MODIFIED_DT,
    RECORD_NM,
    RECORD_NB,
    BDY_PRT_NM,
    INJ_NTR_TX,
    EFFCT_STRT_DT,
    EFFCT_END_DT,
    ACTIVE_FLAG,
    EDW_LAST_UPDT_USER_ID,
    EDW_LAST_UPDT_TS,
    HIGH_ENRGY_HZRD_TX,
    INJRY_SUSTAIN_1_TX,
    INJRY_SUSTAIN_2_TX,
    BDY_PRT_GRP_TX
  FROM NEW_ACTIVE_ROWS
)
SELECT
  BDY_PRT_KEY,
  BDY_PRT_ID,
  INJRY_ILLNSS_ID,
  CREATED_DT,
  MODIFIED_DT,
  RECORD_NM,
  RECORD_NB,
  BDY_PRT_NM,
  INJ_NTR_TX,
  EFFCT_STRT_DT,
  EFFCT_END_DT,
  ACTIVE_FLAG,
  EDW_LAST_UPDT_USER_ID,
  EDW_LAST_UPDT_TS,
  HIGH_ENRGY_HZRD_TX,
  INJRY_SUSTAIN_1_TX,
  INJRY_SUSTAIN_2_TX,
  BDY_PRT_GRP_TX
FROM FINAL_ROWS;

$DESC_TABLE:
name	type	kind	null?	default
BDY_PRT_KEY	NUMBER(10,0)	COLUMN	N	
BDY_PRT_ID	VARCHAR(200)	COLUMN	N	
INJRY_ILLNSS_ID	VARCHAR(200)	COLUMN	N	
CREATED_DT	TIMESTAMP_NTZ(9)	COLUMN	Y	
MODIFIED_DT	TIMESTAMP_NTZ(9)	COLUMN	Y	
RECORD_NM	VARCHAR(200)	COLUMN	Y	
RECORD_NB	VARCHAR(100)	COLUMN	N	
BDY_PRT_NM	VARCHAR(200)	COLUMN	Y	
INJ_NTR_TX	VARCHAR(200)	COLUMN	Y	
EFFCT_STRT_DT	TIMESTAMP_NTZ(9)	COLUMN	Y	
EFFCT_END_DT	TIMESTAMP_NTZ(9)	COLUMN	Y	
ACTIVE_FLAG	VARCHAR(1)	COLUMN	Y	
EDW_LAST_UPDT_USER_ID	VARCHAR(10)	COLUMN	N	
EDW_LAST_UPDT_TS	TIMESTAMP_NTZ(6)	COLUMN	N	CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_NTZ(6))
HIGH_ENRGY_HZRD_TX	VARCHAR(200)	COLUMN	Y	
INJRY_SUSTAIN_1_TX	VARCHAR(200)	COLUMN	Y	
INJRY_SUSTAIN_2_TX	VARCHAR(200)	COLUMN	Y	
BDY_PRT_GRP_TX	VARCHAR(200)	COLUMN	Y	
;
