-- ============================================================
-- CONVERSION SUMMARY
-- ============================================================
-- AUTOSYS_JOB_NAME: TBD
-- 
-- COLUMN NAME MAPPINGS (source -> target, names differ during INSERT):
--   - CLOSED_BY_ID -> CLSD_BY_ID
-- ============================================================

{{ config(
    materialized='incremental',
    unique_key='INCDNT_ID',
    incremental_strategy='merge',
    full_refresh=false,
    pre_hook=[
        log_model_start(this, 'TBD')
    ],
    post_hook=[
        log_model_end(this, 'TBD')
    ]
) }}

WITH
JOB_PARAM AS (
    SELECT PARAM_ID, PARAM_NAME, PARAM_VALUE FROM {{source('CRPDB01_METADATA','SHMSADM_JOB_PARAMETERS')}}
    WHERE JOB_NAME= 'ODS_SHMS_INCDNT' AND AUTOSYS_JOB_NAME = 'TBD' AND ACTIVE_IND = 'Y'
),

JOB_CONTROL AS (
    SELECT JOB_ID, START_DATE, END_DATE FROM {{source('CRPDB01_METADATA','SHMSADM_JOB_CONTROL')}}
    WHERE JOB_NAME= 'ODS_SHMS_INCDNT' AND AUTOSYS_JOB_NAME = 'TBD'
),
SQ_STG_SHMS_EHSINCIDENTMANG_INCIDENTOBJECT AS (
  SELECT
      ID,
      DATECREATED,
      DATEMODIFIED,
      DELETED,
      DESCRIPTION,
      NAME,
      PREVENEVENT,
      RECOMMENDATIONS,
      RECORDNO,
      SUPEDESCRIPTION,
      WHATHAPPENED,
      WHATRESULTED,
      ADDITIONALCOST,
      CORRECTIACTIONS,
      INCIDENTDATE,
      DATEAPPROVED,
      DATEREPORTED,
      DATINVESTIGATED,
      DATOFOCCURRENCE,
      ENDDATE,
      ESTIMATEDCOST,
      EVENTTYPE,
      FINALAPPNOTES,
      IMMEDIATEACTION,
      INVESTDUEDATE,
      INVESTRESULTS,
      NBCAPAS,
      NBOPENEDCAPAS,
      REVIEWNOTES,
      SUMMARY,
      SUSPECTEDCAUSE,
      TOTALCOST,
      APPRVDCOMMENT,
      CAUSE,
      COMMENTS,
      CURRENTTIME,
      DATEINVESTIGATE,
      DISABLEWORKFLOW,
      DITHEEVENTOCCUR,
      EMPLOYEE,
      FINAPPROVEDBY,
      GREATERTHAN260V,
      INCIDEDISPFIELD,
      INVESTCOMMENTS,
      INVESTIGENDDATE,
      INVHISTINFO,
      LOCATIONDESC,
      MARKASPRIVATE,
      MASTERHELPER,
      OPENWORKFLOW,
      OPENWORKSTAGE,
      PROCEGUIDELINES,
      PROFESSCOMMENTS,
      REINVESTIGATOR,
      RELATEDTOMASTER,
      REVIEWCOMMENTS,
      SHIFTSTARTTIME,
      STARTINVESTIGAT,
      TAVALIDINCIDENT,
      WORKFLOWCLOSEDS,
      WORKFLOWSTAGE,
      EVENT_TYPE_ID,
      EVENT_TYPE,
      WORKLOC_ID,
      WORKLOC_RECORDNO,
      ACTIVITY_NM,
      REPORTED_BY_ID,
      REPORTED_BY_NM,
      SEVERITY,
      ACTUAL_SEVERITY,
      WORKFLOW_STATUS,
      LOCATION_ID,
      LOCATION_NM,
      BUSINESS_UNIT,
      CREATED_BY_NM,
      MODIFIED_BY_NM,
      EDW_LAST_UPDT_USER_ID,
      EDW_LAST_UPDT_DTM,
      BODYPART_GROUPS,
      ELECTRICFLASH,
      CLOSED_BY_ID,
      CLOSED_BY_NM,
      IOUTCOMEMAPPING,
      LOCATIONMAPPING,
      STOOUROUTAGEWORK,
      SUPERVISOR_ID,
      SUPERVISOR_NM,
      WACTIVITYGROUPS,
      ESTABLISHMENTID,
      OCCUPATGROUPING,
      GROUPINTOPLEVEL,
      HIENERGYPRESENT,
      HIGHENEINCIDENT,
      INJURYSUSTAIN1,
      INJURYSUSTAIN2,
      DCONTROLPRES1,
      DCONTROLPRES2,
      CAUSEOFEVENT,
      EMPLOYEEINVOLVED,
      TYPEOFEVENT,
      EMPLOYEEINVOLVED_ID,
      HIGHENERGYHAZARD,
      DRUGALCOHOL
    FROM {{ref('STG_SHMS_EHSINCIDENTMANG_INCIDENTOBJECT')}}  --CRPDB01_DEV_SANDBOX.SHMSADM.STG_SHMS_EHSINCIDENTMANG_INCIDENTOBJECT
),
lkp_target AS (
  SELECT
      INCDNT_ID
    FROM {{this}}  --CRPDB01_DEV_SANDBOX.SHMSADM.ODS_SHMS_INCDNT
    QUALIFY ROW_NUMBER() OVER (PARTITION BY INCDNT_ID order by INCDNT_ID)=1
),
exp_getfields AS (
  SELECT
      SQ_STG_SHMS_EHSINCIDENTMANG_INCIDENTOBJECT.* EXCLUDE (EDW_LAST_UPDT_DTM, EDW_LAST_UPDT_USER_ID),
      lkp_lkp_target.INCDNT_ID AS lkp_INCDNT_ID,
      IFF((DATECREATED IS NULL), NULL, TRY_TO_TIMESTAMP_NTZ(COALESCE(CAST(SUBSTR(DATECREATED, 1, 10) AS VARCHAR), '') || ' ' || COALESCE(CAST(SUBSTR(DATECREATED, 12, 8) AS VARCHAR), ''), 'YYYY-MM-DD HH24:MI:SS')) AS out_DATECREATED,
      IFF((DATEMODIFIED IS NULL), NULL, TRY_TO_TIMESTAMP_NTZ(COALESCE(CAST(SUBSTR(DATEMODIFIED, 1, 10) AS VARCHAR), '') || ' ' || COALESCE(CAST(SUBSTR(DATEMODIFIED, 12, 8) AS VARCHAR), ''), 'YYYY-MM-DD HH24:MI:SS')) AS out_DATEMODIFIED,
      IFF((INCIDENTDATE IS NULL), NULL, TRY_TO_TIMESTAMP_NTZ(COALESCE(CAST(SUBSTR(INCIDENTDATE, 1, 10) AS VARCHAR), '') || ' ' || COALESCE(CAST(SUBSTR(INCIDENTDATE, 12, 8) AS VARCHAR), ''), 'YYYY-MM-DD HH24:MI:SS')) AS out_INCIDENTDATE,
      IFF((DATEAPPROVED IS NULL), NULL, TRY_TO_TIMESTAMP_NTZ(COALESCE(CAST(SUBSTR(DATEAPPROVED, 1, 10) AS VARCHAR), '') || ' ' || COALESCE(CAST(SUBSTR(DATEAPPROVED, 12, 8) AS VARCHAR), ''), 'YYYY-MM-DD HH24:MI:SS')) AS out_DATEAPPROVED,
      IFF((DATEREPORTED IS NULL), NULL, TRY_TO_TIMESTAMP_NTZ(COALESCE(CAST(SUBSTR(DATEREPORTED, 1, 10) AS VARCHAR), '') || ' ' || COALESCE(CAST(SUBSTR(DATEREPORTED, 12, 8) AS VARCHAR), ''), 'YYYY-MM-DD HH24:MI:SS')) AS out_DATEREPORTED,
      IFF((DATINVESTIGATED IS NULL), NULL, TRY_TO_TIMESTAMP_NTZ(COALESCE(CAST(SUBSTR(DATINVESTIGATED, 1, 10) AS VARCHAR), '') || ' ' || COALESCE(CAST(SUBSTR(DATINVESTIGATED, 12, 8) AS VARCHAR), ''), 'YYYY-MM-DD HH24:MI:SS')) AS out_DATINVESTIGATED,
      IFF((DATOFOCCURRENCE IS NULL), NULL, TRY_TO_TIMESTAMP_NTZ(COALESCE(CAST(SUBSTR(DATOFOCCURRENCE, 1, 10) AS VARCHAR), '') || ' ' || COALESCE(CAST(SUBSTR(DATOFOCCURRENCE, 12, 8) AS VARCHAR), ''), 'YYYY-MM-DD HH24:MI:SS')) AS out_DATOFOCCURRENCE,
      IFF((ENDDATE IS NULL), NULL, TRY_TO_TIMESTAMP_NTZ(COALESCE(CAST(SUBSTR(ENDDATE, 1, 10) AS VARCHAR), '') || ' ' || COALESCE(CAST(SUBSTR(ENDDATE, 12, 8) AS VARCHAR), ''), 'YYYY-MM-DD HH24:MI:SS')) AS out_ENDDATE,
      IFF((INVESTDUEDATE IS NULL), NULL, TRY_TO_TIMESTAMP_NTZ(COALESCE(CAST(SUBSTR(INVESTDUEDATE, 1, 10) AS VARCHAR), '') || ' ' || COALESCE(CAST(SUBSTR(INVESTDUEDATE, 12, 8) AS VARCHAR), ''), 'YYYY-MM-DD HH24:MI:SS')) AS out_INVESTDUEDATE,
      IFF((CURRENTTIME IS NULL), NULL, TRY_TO_TIMESTAMP_NTZ(COALESCE(CAST(SUBSTR(CURRENTTIME, 1, 10) AS VARCHAR), '') || ' ' || COALESCE(CAST(SUBSTR(CURRENTTIME, 12, 8) AS VARCHAR), ''), 'YYYY-MM-DD HH24:MI:SS')) AS out_CURRENTTIME,
      IFF((INVESTIGENDDATE IS NULL), NULL, TRY_TO_TIMESTAMP_NTZ(COALESCE(CAST(SUBSTR(INVESTIGENDDATE, 1, 10) AS VARCHAR), '') || ' ' || COALESCE(CAST(SUBSTR(INVESTIGENDDATE, 12, 8) AS VARCHAR), ''), 'YYYY-MM-DD HH24:MI:SS')) AS out_INVESTIGENDDATE,
      IFF((SHIFTSTARTTIME IS NULL), NULL, TRY_TO_TIMESTAMP_NTZ(COALESCE(CAST(SUBSTR(SHIFTSTARTTIME, 1, 10) AS VARCHAR), '') || ' ' || COALESCE(CAST(SUBSTR(SHIFTSTARTTIME, 12, 8) AS VARCHAR), ''), 'YYYY-MM-DD HH24:MI:SS')) AS out_SHIFTSTARTTIME,
      'SHMSUSER' AS EDW_LAST_UPDT_USER_ID,
      CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_NTZ(6)) AS EDW_LAST_UPDT_DTM
    FROM SQ_STG_SHMS_EHSINCIDENTMANG_INCIDENTOBJECT
    LEFT JOIN lkp_target lkp_lkp_target
      ON lkp_lkp_target.INCDNT_ID = SQ_STG_SHMS_EHSINCIDENTMANG_INCIDENTOBJECT.ID
)

SELECT
    CAST(LEFT(TRIM(SRC.ID), 50) AS VARCHAR(50)) AS INCDNT_ID,
    SRC.OUT_DATECREATED AS CREATED_DT,
    SRC.OUT_DATEMODIFIED AS MODIFIED_DT,
    CAST(LEFT(TRIM(SRC.DELETED), 10) AS VARCHAR(10)) AS DLTD_FL,
    CAST(LEFT(TRIM(SRC.DESCRIPTION), 16777216) AS VARCHAR(16777216)) AS DESC_TX,
    CAST(LEFT(TRIM(SRC.NAME), 50) AS VARCHAR(50)) AS INCDNT_NM,
    CAST(LEFT(TRIM(SRC.PREVENEVENT), 16777216) AS VARCHAR(16777216)) AS PRVNT_EVNT_TX,
    CAST(LEFT(TRIM(SRC.RECOMMENDATIONS), 16777216) AS VARCHAR(16777216)) AS RCMNDTNS_TX,
    TRY_TO_NUMBER(TRIM(SRC.RECORDNO)) AS RECORD_NB,
    CAST(LEFT(TRIM(SRC.SUPEDESCRIPTION), 16777216) AS VARCHAR(16777216)) AS SUPRVSR_DESC_TX,
    CAST(LEFT(TRIM(SRC.WHATHAPPENED), 16777216) AS VARCHAR(16777216)) AS WHAT_HPPND_TX,
    CAST(LEFT(TRIM(SRC.WHATRESULTED), 16777216) AS VARCHAR(16777216)) AS WHAT_RSLTD_TX,
    TRY_TO_NUMBER(TRIM(SRC.ADDITIONALCOST)) AS ADDTNL_CST_AMT,
    CAST(LEFT(TRIM(SRC.CORRECTIACTIONS), 16777216) AS VARCHAR(16777216)) AS CRRCTV_ACTNS_TX,
    SRC.OUT_INCIDENTDATE AS INCDNT_DT,
    SRC.OUT_DATEAPPROVED AS APPRVD_DT,
    SRC.OUT_DATEREPORTED AS REPRTD_DT,
    SRC.OUT_DATINVESTIGATED AS INVSTGTD_DT,
    SRC.OUT_DATOFOCCURRENCE AS OCCRNC_DT,
    SRC.OUT_ENDDATE AS END_DT,
    TRY_TO_NUMBER(TRIM(SRC.ESTIMATEDCOST)) AS ESTMTD_CST_AMT,
    CAST(LEFT(TRIM(SRC.EVENTTYPE), 25) AS VARCHAR(25)) AS EVNT_TYP_CD,
    CAST(LEFT(TRIM(SRC.FINALAPPNOTES), 16777216) AS VARCHAR(16777216)) AS FNL_APP_NOTES_TX,
    CAST(LEFT(TRIM(SRC.IMMEDIATEACTION), 16777216) AS VARCHAR(16777216)) AS IMMDT_ACTN_TX,
    SRC.OUT_INVESTDUEDATE AS INVST_DUE_DT,
    CAST(LEFT(TRIM(SRC.INVESTRESULTS), 25) AS VARCHAR(25)) AS INVST_RSLTS_TX,
    TRY_TO_NUMBER(TRIM(SRC.NBCAPAS)) AS CAPAS_NB,
    TRY_TO_NUMBER(TRIM(SRC.NBOPENEDCAPAS)) AS OPND_CAPAS_NB,
    CAST(LEFT(TRIM(SRC.REVIEWNOTES), 500) AS VARCHAR(500)) AS RVW_NOTES_TX,
    CAST(LEFT(TRIM(SRC.SUMMARY), 250) AS VARCHAR(250)) AS SMMRY_TX,
    TRY_TO_NUMBER(TRIM(SRC.TOTALCOST)) AS TOT_CST_AMT,
    CAST(LEFT(TRIM(SRC.APPRVDCOMMENT), 250) AS VARCHAR(250)) AS APPRVD_CMMNT_TX,
    CAST(LEFT(TRIM(SRC.CAUSE), 25) AS VARCHAR(25)) AS CAUSE_TX,
    CAST(LEFT(TRIM(SRC.COMMENTS), 16777216) AS VARCHAR(16777216)) AS CMMNTS_TX,
    SRC.OUT_CURRENTTIME AS CRRNT_DTM,
    TRY_TO_TIMESTAMP_NTZ(NULLIF(TRIM(SRC.DATEINVESTIGATE), ''), 'YYYY-MM-DD HH24:MI:SS') AS INVSTGT_DT,
    CAST(LEFT(TRIM(SRC.DISABLEWORKFLOW), 25) AS VARCHAR(25)) AS DSBL_WRKFLW_FL,
    CAST(LEFT(TRIM(SRC.DITHEEVENTOCCUR), 16777216) AS VARCHAR(16777216)) AS EVNT_OCCR_TX,
    CAST(LEFT(TRIM(SRC.EMPLOYEE), 25) AS VARCHAR(25)) AS EMP_TX,
    CAST(LEFT(TRIM(SRC.FINAPPROVEDBY), 25) AS VARCHAR(25)) AS FIN_APPRVD_BY_TX,
    CAST(LEFT(TRIM(SRC.GREATERTHAN260V), 25) AS VARCHAR(25)) AS GRTR_THN_260V_FL,
    CAST(LEFT(TRIM(SRC.INCIDEDISPFIELD), 50) AS VARCHAR(50)) AS INCDNT_DSPLY_FLD_TX,
    CAST(LEFT(TRIM(SRC.INVESTCOMMENTS), 16777216) AS VARCHAR(16777216)) AS INVST_CMMNTS_TX,
    SRC.OUT_INVESTIGENDDATE AS INVSTGT_END_DT,
    CAST(LEFT(TRIM(SRC.INVHISTINFO), 25) AS VARCHAR(25)) AS INV_HIST_INFO_TX,
    CAST(LEFT(TRIM(SRC.LOCATIONDESC), 500) AS VARCHAR(500)) AS LOC_DESC_TX,
    CAST(LEFT(TRIM(SRC.MARKASPRIVATE), 25) AS VARCHAR(25)) AS MARK_AS_PRVT_FL,
    CAST(LEFT(TRIM(SRC.MASTERHELPER), 25) AS VARCHAR(25)) AS MSTR_HLPR_TX,
    CAST(LEFT(TRIM(SRC.OPENWORKFLOW), 25) AS VARCHAR(25)) AS OPN_WRKFLW_FL,
    CAST(LEFT(TRIM(SRC.OPENWORKSTAGE), 25) AS VARCHAR(25)) AS OPN_WRKSTG_TX,
    CAST(LEFT(TRIM(SRC.PROCEGUIDELINES), 16777216) AS VARCHAR(16777216)) AS PROC_GUDLNS_TX,
    CAST(LEFT(TRIM(SRC.PROFESSCOMMENTS), 16777216) AS VARCHAR(16777216)) AS PROF_CMMNTS_TX,
    CAST(LEFT(TRIM(SRC.REINVESTIGATOR), 25) AS VARCHAR(25)) AS RE_INVSTGTR_TX,
    CAST(LEFT(TRIM(SRC.RELATEDTOMASTER), 25) AS VARCHAR(25)) AS RLTD_TO_MSTR_FL,
    CAST(LEFT(TRIM(SRC.REVIEWCOMMENTS), 25) AS VARCHAR(25)) AS RVW_CMMNTS_TX,
    SRC.OUT_SHIFTSTARTTIME AS SHFT_START_DTM,
    CAST(LEFT(TRIM(SRC.STARTINVESTIGAT), 25) AS VARCHAR(25)) AS INVSTGTN_START_FL,
    CAST(LEFT(TRIM(SRC.TAVALIDINCIDENT), 25) AS VARCHAR(25)) AS TA_VLD_INCDNT_FL,
    CAST(LEFT(TRIM(SRC.WORKFLOWCLOSEDS), 25) AS VARCHAR(25)) AS WRKFLW_CLSD_FL,
    CAST(LEFT(TRIM(SRC.WORKFLOWSTAGE), 25) AS VARCHAR(25)) AS WRKFLW_STG_TX,
    CAST(LEFT(TRIM(SRC.EVENT_TYPE_ID), 50) AS VARCHAR(50)) AS EVNT_TYP_ID,
    CAST(LEFT(TRIM(SRC.EVENT_TYPE), 50) AS VARCHAR(50)) AS EVNT_TYP_NM,
    CAST(LEFT(TRIM(SRC.WORKLOC_ID), 50) AS VARCHAR(50)) AS WRK_LOC_ID,
    TRY_TO_NUMBER(TRIM(SRC.WORKLOC_RECORDNO)) AS WRK_LOC_RCRD_NB,
    CAST(LEFT(TRIM(SRC.ACTIVITY_NM), 50) AS VARCHAR(50)) AS ACTVTY_NM,
    CAST(LEFT(TRIM(SRC.REPORTED_BY_ID), 50) AS VARCHAR(50)) AS RPRTD_BY_ID,
    CAST(LEFT(TRIM(SRC.REPORTED_BY_NM), 100) AS VARCHAR(100)) AS RPRTD_BY_NM,
    CAST(LEFT(TRIM(SRC.SEVERITY), 40) AS VARCHAR(40)) AS SVRTY_TX,
    CAST(LEFT(TRIM(SRC.ACTUAL_SEVERITY), 40) AS VARCHAR(40)) AS ACTL_SVRTY_TX,
    CAST(LEFT(TRIM(SRC.WORKFLOW_STATUS), 40) AS VARCHAR(40)) AS WRKFLW_STAT_TX,
    CAST(LEFT(TRIM(SRC.LOCATION_ID), 50) AS VARCHAR(50)) AS LOC_ID,
    CAST(LEFT(TRIM(SRC.LOCATION_NM), 100) AS VARCHAR(100)) AS LOC_NM,
    CAST(LEFT(TRIM(SRC.BUSINESS_UNIT), 50) AS VARCHAR(50)) AS BUS_UNIT_TX,
    CAST(LEFT(TRIM(SRC.CREATED_BY_NM), 100) AS VARCHAR(100)) AS CREATD_BY_NM,
    CAST(LEFT(TRIM(SRC.MODIFIED_BY_NM), 100) AS VARCHAR(100)) AS MODFD_BY_NM,
    CAST(LEFT(TRIM(SRC.BODYPART_GROUPS), 50) AS VARCHAR(50)) AS BDY_PRT_GRP_TX,
    CAST(LEFT(TRIM(SRC.ELECTRICFLASH), 5) AS VARCHAR(5)) AS ELCTRC_FLSH_FL,
    CAST(LEFT(TRIM(COALESCE(TGT.CLSD_BY_ID, SRC.CLOSED_BY_ID)), 50) AS VARCHAR(50)) AS CLSD_BY_ID,
    CAST(LEFT(TRIM(SRC.CLOSED_BY_NM), 100) AS VARCHAR(100)) AS CLSD_BY_NM,
    CAST(LEFT(TRIM(SRC.IOUTCOMEMAPPING), 50) AS VARCHAR(50)) AS IOUTCM_MPPNG_TX,
    CAST(LEFT(TRIM(SRC.LOCATIONMAPPING), 50) AS VARCHAR(50)) AS LOC_MPPNG_TX,
    CAST(LEFT(TRIM(SRC.STOOUROUTAGEWORK), 50) AS VARCHAR(50)) AS ST_OUTG_WRK_TX,
    CAST(LEFT(TRIM(SRC.SUPERVISOR_ID), 50) AS VARCHAR(50)) AS SPRVSR_ID,
    CAST(LEFT(TRIM(SRC.SUPERVISOR_NM), 100) AS VARCHAR(100)) AS SPRVSR_NM,
    CAST(LEFT(TRIM(SRC.WACTIVITYGROUPS), 50) AS VARCHAR(50)) AS WACTV_GRPS_TX,
    CAST(LEFT(TRIM(SRC.ESTABLISHMENTID), 50) AS VARCHAR(50)) AS ESTBLSHMNT_ID,
    CAST(LEFT(TRIM(SRC.OCCUPATGROUPING), 50) AS VARCHAR(50)) AS OCCPTN_GRPNG_TX,
    CAST(LEFT(TRIM(SRC.GROUPINTOPLEVEL), 50) AS VARCHAR(50)) AS GRPNG_TOPLVL_TX,
    CAST(LEFT(TRIM(SRC.HIENERGYPRESENT), 50) AS VARCHAR(50)) AS HGH_ENRGY_PRSNT_TX,
    CAST(LEFT(TRIM(SRC.HIGHENEINCIDENT), 50) AS VARCHAR(50)) AS HGH_ENRGY_INCDNT_TX,
    CAST(LEFT(TRIM(SRC.INJURYSUSTAIN1), 50) AS VARCHAR(50)) AS INJRY_SUSTAIN_1_TX,
    CAST(LEFT(TRIM(SRC.INJURYSUSTAIN2), 50) AS VARCHAR(50)) AS INJRY_SUSTAIN_2_TX,
    CAST(LEFT(TRIM(SRC.DCONTROLPRES1), 50) AS VARCHAR(50)) AS DCNTRL_PRS_1_TX,
    CAST(LEFT(TRIM(SRC.DCONTROLPRES2), 50) AS VARCHAR(50)) AS DCNTRL_PRS_2_TX,
    CAST(LEFT(TRIM(SRC.CAUSEOFEVENT), 16777216) AS VARCHAR(16777216)) AS CAUSE_EVNT_TX,
    CAST(LEFT(TRIM(SRC.EDW_LAST_UPDT_USER_ID), 20) AS VARCHAR(20)) AS EDW_LAST_UPDT_USER_ID,
    SRC.EDW_LAST_UPDT_DTM,
    CAST(LEFT(TRIM(SRC.EMPLOYEEINVOLVED_ID), 50) AS VARCHAR(50)) AS EMP_INVOLVED_ID,
    CAST(LEFT(TRIM(SRC.EMPLOYEEINVOLVED), 100) AS VARCHAR(100)) AS EMP_INVOLVED_NM,
    CAST(LEFT(TRIM(SRC.TYPEOFEVENT), 100) AS VARCHAR(100)) AS TYP_OF_EVNT_TX,
    CAST(LEFT(TRIM(SRC.HIGHENERGYHAZARD), 200) AS VARCHAR(200)) AS HIGH_ENRGY_HZRD_TX,
    CAST(LEFT(TRIM(SRC.DRUGALCOHOL), 50) AS VARCHAR(50)) AS DRUGALCOHOL_FL

FROM
    exp_getfields SRC
LEFT JOIN
    {{this}} TGT
ON
    SRC.ID = TGT.INCDNT_ID
WHERE
  (
   DECODE(CAST(LEFT(TRIM(tgt.MODFD_BY_NM), 100) AS VARCHAR(100)), CAST(LEFT(TRIM(src.MODIFIED_BY_NM), 100) AS VARCHAR(100)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.BDY_PRT_GRP_TX), 50) AS VARCHAR(50)), CAST(LEFT(TRIM(src.BODYPART_GROUPS), 50) AS VARCHAR(50)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.ELCTRC_FLSH_FL), 5) AS VARCHAR(5)), CAST(LEFT(TRIM(src.ELECTRICFLASH), 5) AS VARCHAR(5)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.CLSD_BY_NM), 100) AS VARCHAR(100)), CAST(LEFT(TRIM(src.CLOSED_BY_NM), 100) AS VARCHAR(100)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.IOUTCM_MPPNG_TX), 50) AS VARCHAR(50)), CAST(LEFT(TRIM(src.IOUTCOMEMAPPING), 50) AS VARCHAR(50)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.LOC_MPPNG_TX), 50) AS VARCHAR(50)), CAST(LEFT(TRIM(src.LOCATIONMAPPING), 50) AS VARCHAR(50)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.ST_OUTG_WRK_TX), 50) AS VARCHAR(50)), CAST(LEFT(TRIM(src.STOOUROUTAGEWORK), 50) AS VARCHAR(50)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.SPRVSR_ID), 50) AS VARCHAR(50)), CAST(LEFT(TRIM(src.SUPERVISOR_ID), 50) AS VARCHAR(50)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.SPRVSR_NM), 100) AS VARCHAR(100)), CAST(LEFT(TRIM(src.SUPERVISOR_NM), 100) AS VARCHAR(100)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.WACTV_GRPS_TX), 50) AS VARCHAR(50)), CAST(LEFT(TRIM(src.WACTIVITYGROUPS), 50) AS VARCHAR(50)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.ESTBLSHMNT_ID), 50) AS VARCHAR(50)), CAST(LEFT(TRIM(src.ESTABLISHMENTID), 50) AS VARCHAR(50)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.EDW_LAST_UPDT_USER_ID), 20) AS VARCHAR(20)), CAST(LEFT(TRIM(src.EDW_LAST_UPDT_USER_ID), 20) AS VARCHAR(20)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.EMP_INVOLVED_ID), 50) AS VARCHAR(50)), CAST(LEFT(TRIM(src.EMPLOYEEINVOLVED_ID), 50) AS VARCHAR(50)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.HIGH_ENRGY_HZRD_TX), 200) AS VARCHAR(200)), CAST(LEFT(TRIM(src.HIGHENERGYHAZARD), 200) AS VARCHAR(200)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.DRUGALCOHOL_FL), 50) AS VARCHAR(50)), CAST(LEFT(TRIM(src.DRUGALCOHOL), 50) AS VARCHAR(50)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.INCDNT_NM), 50) AS VARCHAR(50)), CAST(LEFT(TRIM(src.NAME), 50) AS VARCHAR(50)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.PRVNT_EVNT_TX), 16777216) AS VARCHAR(16777216)), CAST(LEFT(TRIM(src.PREVENEVENT), 16777216) AS VARCHAR(16777216)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.RCMNDTNS_TX), 16777216) AS VARCHAR(16777216)), CAST(LEFT(TRIM(src.RECOMMENDATIONS), 16777216) AS VARCHAR(16777216)), 1, 0) = 0 OR
   DECODE(CAST(TRIM(tgt.RECORD_NB) AS NUMBER(38,18)), TRY_TO_NUMBER(TRIM(src.RECORDNO)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.SUPRVSR_DESC_TX), 16777216) AS VARCHAR(16777216)), CAST(LEFT(TRIM(src.SUPEDESCRIPTION), 16777216) AS VARCHAR(16777216)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.WHAT_HPPND_TX), 16777216) AS VARCHAR(16777216)), CAST(LEFT(TRIM(src.WHATHAPPENED), 16777216) AS VARCHAR(16777216)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.WHAT_RSLTD_TX), 16777216) AS VARCHAR(16777216)), CAST(LEFT(TRIM(src.WHATRESULTED), 16777216) AS VARCHAR(16777216)), 1, 0) = 0 OR
   DECODE(CAST(TRIM(tgt.ADDTNL_CST_AMT) AS NUMBER(38,18)), TRY_TO_NUMBER(TRIM(src.ADDITIONALCOST)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.CRRCTV_ACTNS_TX), 16777216) AS VARCHAR(16777216)), CAST(LEFT(TRIM(src.CORRECTIACTIONS), 16777216) AS VARCHAR(16777216)), 1, 0) = 0 OR
   DECODE(CAST(tgt.END_DT AS TIMESTAMP_NTZ(9)), src.OUT_ENDDATE, 1, 0) = 0 OR
   DECODE(CAST(TRIM(tgt.ESTMTD_CST_AMT) AS NUMBER(38,18)), TRY_TO_NUMBER(TRIM(src.ESTIMATEDCOST)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.EVNT_TYP_CD), 25) AS VARCHAR(25)), CAST(LEFT(TRIM(src.EVENTTYPE), 25) AS VARCHAR(25)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.FNL_APP_NOTES_TX), 16777216) AS VARCHAR(16777216)), CAST(LEFT(TRIM(src.FINALAPPNOTES), 16777216) AS VARCHAR(16777216)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.IMMDT_ACTN_TX), 16777216) AS VARCHAR(16777216)), CAST(LEFT(TRIM(src.IMMEDIATEACTION), 16777216) AS VARCHAR(16777216)), 1, 0) = 0 OR
   DECODE(CAST(tgt.INVST_DUE_DT AS TIMESTAMP_NTZ(9)), src.OUT_INVESTDUEDATE, 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.INVST_RSLTS_TX), 25) AS VARCHAR(25)), CAST(LEFT(TRIM(src.INVESTRESULTS), 25) AS VARCHAR(25)), 1, 0) = 0 OR
   DECODE(CAST(TRIM(tgt.CAPAS_NB) AS NUMBER(38,18)), TRY_TO_NUMBER(TRIM(src.NBCAPAS)), 1, 0) = 0 OR
   DECODE(CAST(TRIM(tgt.OPND_CAPAS_NB) AS NUMBER(38,18)), TRY_TO_NUMBER(TRIM(src.NBOPENEDCAPAS)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.RVW_NOTES_TX), 500) AS VARCHAR(500)), CAST(LEFT(TRIM(src.REVIEWNOTES), 500) AS VARCHAR(500)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.SMMRY_TX), 250) AS VARCHAR(250)), CAST(LEFT(TRIM(src.SUMMARY), 250) AS VARCHAR(250)), 1, 0) = 0 OR
   DECODE(CAST(TRIM(tgt.TOT_CST_AMT) AS NUMBER(38,18)), TRY_TO_NUMBER(TRIM(src.TOTALCOST)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.APPRVD_CMMNT_TX), 250) AS VARCHAR(250)), CAST(LEFT(TRIM(src.APPRVDCOMMENT), 250) AS VARCHAR(250)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.CAUSE_TX), 25) AS VARCHAR(25)), CAST(LEFT(TRIM(src.CAUSE), 25) AS VARCHAR(25)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.CMMNTS_TX), 16777216) AS VARCHAR(16777216)), CAST(LEFT(TRIM(src.COMMENTS), 16777216) AS VARCHAR(16777216)), 1, 0) = 0 OR
   DECODE(CAST(tgt.CRRNT_DTM AS TIMESTAMP_NTZ(6)), src.OUT_CURRENTTIME, 1, 0) = 0 OR
   DECODE(CAST(tgt.INVSTGT_DT AS TIMESTAMP_NTZ(9)), TRY_TO_TIMESTAMP_NTZ(NULLIF(TRIM(src.DATEINVESTIGATE), ''), 'YYYY-MM-DD HH24:MI:SS'), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.DSBL_WRKFLW_FL), 25) AS VARCHAR(25)), CAST(LEFT(TRIM(src.DISABLEWORKFLOW), 25) AS VARCHAR(25)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.EVNT_OCCR_TX), 16777216) AS VARCHAR(16777216)), CAST(LEFT(TRIM(src.DITHEEVENTOCCUR), 16777216) AS VARCHAR(16777216)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.EMP_TX), 25) AS VARCHAR(25)), CAST(LEFT(TRIM(src.EMPLOYEE), 25) AS VARCHAR(25)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.FIN_APPRVD_BY_TX), 25) AS VARCHAR(25)), CAST(LEFT(TRIM(src.FINAPPROVEDBY), 25) AS VARCHAR(25)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.GRTR_THN_260V_FL), 25) AS VARCHAR(25)), CAST(LEFT(TRIM(src.GREATERTHAN260V), 25) AS VARCHAR(25)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.INCDNT_DSPLY_FLD_TX), 50) AS VARCHAR(50)), CAST(LEFT(TRIM(src.INCIDEDISPFIELD), 50) AS VARCHAR(50)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.INVST_CMMNTS_TX), 16777216) AS VARCHAR(16777216)), CAST(LEFT(TRIM(src.INVESTCOMMENTS), 16777216) AS VARCHAR(16777216)), 1, 0) = 0 OR
   DECODE(CAST(tgt.INVSTGT_END_DT AS TIMESTAMP_NTZ(9)), src.OUT_INVESTIGENDDATE, 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.INV_HIST_INFO_TX), 25) AS VARCHAR(25)), CAST(LEFT(TRIM(src.INVHISTINFO), 25) AS VARCHAR(25)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.LOC_DESC_TX), 500) AS VARCHAR(500)), CAST(LEFT(TRIM(src.LOCATIONDESC), 500) AS VARCHAR(500)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.MARK_AS_PRVT_FL), 25) AS VARCHAR(25)), CAST(LEFT(TRIM(src.MARKASPRIVATE), 25) AS VARCHAR(25)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.MSTR_HLPR_TX), 25) AS VARCHAR(25)), CAST(LEFT(TRIM(src.MASTERHELPER), 25) AS VARCHAR(25)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.OPN_WRKFLW_FL), 25) AS VARCHAR(25)), CAST(LEFT(TRIM(src.OPENWORKFLOW), 25) AS VARCHAR(25)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.OPN_WRKSTG_TX), 25) AS VARCHAR(25)), CAST(LEFT(TRIM(src.OPENWORKSTAGE), 25) AS VARCHAR(25)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.PROC_GUDLNS_TX), 16777216) AS VARCHAR(16777216)), CAST(LEFT(TRIM(src.PROCEGUIDELINES), 16777216) AS VARCHAR(16777216)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.PROF_CMMNTS_TX), 16777216) AS VARCHAR(16777216)), CAST(LEFT(TRIM(src.PROFESSCOMMENTS), 16777216) AS VARCHAR(16777216)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.RE_INVSTGTR_TX), 25) AS VARCHAR(25)), CAST(LEFT(TRIM(src.REINVESTIGATOR), 25) AS VARCHAR(25)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.RLTD_TO_MSTR_FL), 25) AS VARCHAR(25)), CAST(LEFT(TRIM(src.RELATEDTOMASTER), 25) AS VARCHAR(25)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.RVW_CMMNTS_TX), 25) AS VARCHAR(25)), CAST(LEFT(TRIM(src.REVIEWCOMMENTS), 25) AS VARCHAR(25)), 1, 0) = 0 OR
   DECODE(CAST(tgt.SHFT_START_DTM AS TIMESTAMP_NTZ(6)), src.OUT_SHIFTSTARTTIME, 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.INVSTGTN_START_FL), 25) AS VARCHAR(25)), CAST(LEFT(TRIM(src.STARTINVESTIGAT), 25) AS VARCHAR(25)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.TA_VLD_INCDNT_FL), 25) AS VARCHAR(25)), CAST(LEFT(TRIM(src.TAVALIDINCIDENT), 25) AS VARCHAR(25)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.WRKFLW_CLSD_FL), 25) AS VARCHAR(25)), CAST(LEFT(TRIM(src.WORKFLOWCLOSEDS), 25) AS VARCHAR(25)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.WRKFLW_STG_TX), 25) AS VARCHAR(25)), CAST(LEFT(TRIM(src.WORKFLOWSTAGE), 25) AS VARCHAR(25)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.GRPNG_TOPLVL_TX), 50) AS VARCHAR(50)), CAST(LEFT(TRIM(src.GROUPINTOPLEVEL), 50) AS VARCHAR(50)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.HGH_ENRGY_PRSNT_TX), 50) AS VARCHAR(50)), CAST(LEFT(TRIM(src.HIENERGYPRESENT), 50) AS VARCHAR(50)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.INJRY_SUSTAIN_1_TX), 50) AS VARCHAR(50)), CAST(LEFT(TRIM(src.INJURYSUSTAIN1), 50) AS VARCHAR(50)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.OCCPTN_GRPNG_TX), 50) AS VARCHAR(50)), CAST(LEFT(TRIM(src.OCCUPATGROUPING), 50) AS VARCHAR(50)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.HGH_ENRGY_INCDNT_TX), 50) AS VARCHAR(50)), CAST(LEFT(TRIM(src.HIGHENEINCIDENT), 50) AS VARCHAR(50)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.INJRY_SUSTAIN_2_TX), 50) AS VARCHAR(50)), CAST(LEFT(TRIM(src.INJURYSUSTAIN2), 50) AS VARCHAR(50)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.DCNTRL_PRS_1_TX), 50) AS VARCHAR(50)), CAST(LEFT(TRIM(src.DCONTROLPRES1), 50) AS VARCHAR(50)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.DCNTRL_PRS_2_TX), 50) AS VARCHAR(50)), CAST(LEFT(TRIM(src.DCONTROLPRES2), 50) AS VARCHAR(50)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.CAUSE_EVNT_TX), 16777216) AS VARCHAR(16777216)), CAST(LEFT(TRIM(src.CAUSEOFEVENT), 16777216) AS VARCHAR(16777216)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.EMP_INVOLVED_NM), 100) AS VARCHAR(100)), CAST(LEFT(TRIM(src.EMPLOYEEINVOLVED), 100) AS VARCHAR(100)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.TYP_OF_EVNT_TX), 100) AS VARCHAR(100)), CAST(LEFT(TRIM(src.TYPEOFEVENT), 100) AS VARCHAR(100)), 1, 0) = 0 OR
   DECODE(CAST(tgt.CREATED_DT AS TIMESTAMP_NTZ(9)), src.OUT_DATECREATED, 1, 0) = 0 OR
   DECODE(CAST(tgt.MODIFIED_DT AS TIMESTAMP_NTZ(9)), src.OUT_DATEMODIFIED, 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.DLTD_FL), 10) AS VARCHAR(10)), CAST(LEFT(TRIM(src.DELETED), 10) AS VARCHAR(10)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.DESC_TX), 16777216) AS VARCHAR(16777216)), CAST(LEFT(TRIM(src.DESCRIPTION), 16777216) AS VARCHAR(16777216)), 1, 0) = 0 OR
   DECODE(CAST(tgt.INCDNT_DT AS TIMESTAMP_NTZ(9)), src.OUT_INCIDENTDATE, 1, 0) = 0 OR
   DECODE(CAST(tgt.APPRVD_DT AS TIMESTAMP_NTZ(9)), src.OUT_DATEAPPROVED, 1, 0) = 0 OR
   DECODE(CAST(tgt.REPRTD_DT AS TIMESTAMP_NTZ(9)), src.OUT_DATEREPORTED, 1, 0) = 0 OR
   DECODE(CAST(tgt.INVSTGTD_DT AS TIMESTAMP_NTZ(9)), src.OUT_DATINVESTIGATED, 1, 0) = 0 OR
   DECODE(CAST(tgt.OCCRNC_DT AS TIMESTAMP_NTZ(9)), src.OUT_DATOFOCCURRENCE, 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.EVNT_TYP_ID), 50) AS VARCHAR(50)), CAST(LEFT(TRIM(src.EVENT_TYPE_ID), 50) AS VARCHAR(50)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.EVNT_TYP_NM), 50) AS VARCHAR(50)), CAST(LEFT(TRIM(src.EVENT_TYPE), 50) AS VARCHAR(50)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.WRK_LOC_ID), 50) AS VARCHAR(50)), CAST(LEFT(TRIM(src.WORKLOC_ID), 50) AS VARCHAR(50)), 1, 0) = 0 OR
   DECODE(CAST(TRIM(tgt.WRK_LOC_RCRD_NB) AS NUMBER(38,18)), TRY_TO_NUMBER(TRIM(src.WORKLOC_RECORDNO)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.ACTVTY_NM), 50) AS VARCHAR(50)), CAST(LEFT(TRIM(src.ACTIVITY_NM), 50) AS VARCHAR(50)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.RPRTD_BY_ID), 50) AS VARCHAR(50)), CAST(LEFT(TRIM(src.REPORTED_BY_ID), 50) AS VARCHAR(50)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.RPRTD_BY_NM), 100) AS VARCHAR(100)), CAST(LEFT(TRIM(src.REPORTED_BY_NM), 100) AS VARCHAR(100)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.SVRTY_TX), 40) AS VARCHAR(40)), CAST(LEFT(TRIM(src.SEVERITY), 40) AS VARCHAR(40)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.ACTL_SVRTY_TX), 40) AS VARCHAR(40)), CAST(LEFT(TRIM(src.ACTUAL_SEVERITY), 40) AS VARCHAR(40)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.WRKFLW_STAT_TX), 40) AS VARCHAR(40)), CAST(LEFT(TRIM(src.WORKFLOW_STATUS), 40) AS VARCHAR(40)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.LOC_ID), 50) AS VARCHAR(50)), CAST(LEFT(TRIM(src.LOCATION_ID), 50) AS VARCHAR(50)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.LOC_NM), 100) AS VARCHAR(100)), CAST(LEFT(TRIM(src.LOCATION_NM), 100) AS VARCHAR(100)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.BUS_UNIT_TX), 50) AS VARCHAR(50)), CAST(LEFT(TRIM(src.BUSINESS_UNIT), 50) AS VARCHAR(50)), 1, 0) = 0 OR
   DECODE(CAST(LEFT(TRIM(tgt.CREATD_BY_NM), 100) AS VARCHAR(100)), CAST(LEFT(TRIM(src.CREATED_BY_NM), 100) AS VARCHAR(100)), 1, 0) = 0
   --DECODE(CAST(TRIM(tgt.EDW_LAST_UPDT_DTM) AS TIMESTAMP_NTZ(6)), CAST(TRIM(src.EDW_LAST_UPDT_DTM) AS TIMESTAMP_NTZ(6)), 1, 0) = 0  -- AUDIT COLUMN, MAY NOT BE NEEDED - PLEASE VERIFY
  )
