{{ config(
    materialized='incremental',
    unique_key='RPRTNG_ID',
    incremental_strategy='merge',
    full_refresh=false,
    pre_hook=[
        log_model_start(this, '/* TODO: set $AUTOSYS_JOB_NAME */')
    ],
    post_hook=[
        log_model_end(this, '/* TODO: set $AUTOSYS_JOB_NAME */')
    ]
) }}

WITH
JOB_PARAM AS (
    SELECT PARAM_ID, PARAM_NAME, PARAM_VALUE FROM {{source('CRPDB01_METADATA','SHMSADM_JOB_PARAMETERS')}}
    WHERE JOB_NAME= 'SHEMS_RPRTNG_GRP_DIM' AND AUTOSYS_JOB_NAME = '/* TODO: set $AUTOSYS_JOB_NAME */' AND ACTIVE_IND = 'Y'
),

JOB_CONTROL AS (
    SELECT JOB_ID, START_DATE, END_DATE FROM {{source('CRPDB01_METADATA','SHMSADM_JOB_CONTROL')}}
    WHERE JOB_NAME= 'SHEMS_RPRTNG_GRP_DIM' AND AUTOSYS_JOB_NAME = '/* TODO: set $AUTOSYS_JOB_NAME */'
),
SQ_ODS_SHMS_LOC_ENTTY AS (
  SELECT
        A.LOC_CD,
        A.RPT_GRPLVL_1_VAL_TX,
        A.RPT_GRPLVL_2_VAL_TX,
        A.RPT_GRPLVL_3_VAL_TX,
        A.RPT_GRPLVL_4_VAL_TX,
        A.HRCHY_LVL_2_TX
      FROM
        {{source('CRPDB01_COMMON','ODS_SHMS_LOC_ENTTY_TEST')}} A  --CRPDB01_DEV_SANDBOX.COMMON.ODS_SHMS_LOC_ENTTY_TEST
      WHERE
        A.RPT_GRPLVL_1_VAL_TX NOT IN('na')
),
LKPTRANS AS (
  SELECT
        SQ_ODS_SHMS_LOC_ENTTY.*,
        _lkp_LKPTRANS.LKP_RPRTNG_ID,
        _lkp_LKPTRANS.LKP_RPT_GRPLVL_1_VAL_TX,
        _lkp_LKPTRANS.LKP_RPT_GRPLVL_2_VAL_TX,
        _lkp_LKPTRANS.LKP_RPT_GRPLVL_3_VAL_TX,
        _lkp_LKPTRANS.LKP_RPT_GRPLVL_4_VAL_TX,
        _lkp_LKPTRANS.LKP_LOC_CD,
        SQ_ODS_SHMS_LOC_ENTTY.LOC_CD AS SRC_LOC_CD,
        _lkp_LKPTRANS.LKP_BUSINESS_UNIT_GRP
      FROM
        SQ_ODS_SHMS_LOC_ENTTY
        LEFT JOIN (
          SELECT
            DIM.RPRTNG_ID as LKP_RPRTNG_ID,
            DIM.LOC_CD as LKP_LOC_CD,
            DIM.RPT_GRPLVL_1_VAL_TX as LKP_RPT_GRPLVL_1_VAL_TX,
            DIM.RPT_GRPLVL_2_VAL_TX as LKP_RPT_GRPLVL_2_VAL_TX,
            DIM.RPT_GRPLVL_3_VAL_TX as LKP_RPT_GRPLVL_3_VAL_TX,
            DIM.RPT_GRPLVL_4_VAL_TX as LKP_RPT_GRPLVL_4_VAL_TX,
            DIM.BUSINESS_UNIT_GRP as LKP_BUSINESS_UNIT_GRP
          FROM
            {{this}} DIM  --CRPDB01_DEV_SANDBOX.SHMSADM.SHEMS_RPRTNG_GRP_DIM
        ) _lkp_LKPTRANS ON _lkp_LKPTRANS.LKP_LOC_CD = SQ_ODS_SHMS_LOC_ENTTY.LOC_CD
),
EXPTRANS_step1 AS (
  SELECT
        SQ_ODS_SHMS_LOC_ENTTY.*,
        lkp_LKPTRANS.LKP_RPRTNG_ID,
        lkp_LKPTRANS.LKP_RPT_GRPLVL_1_VAL_TX,
        lkp_LKPTRANS.LKP_RPT_GRPLVL_2_VAL_TX,
        lkp_LKPTRANS.LKP_RPT_GRPLVL_3_VAL_TX,
        lkp_LKPTRANS.LKP_RPT_GRPLVL_4_VAL_TX,
        lkp_LKPTRANS.LKP_LOC_CD,
        lkp_LKPTRANS.LKP_BUSINESS_UNIT_GRP,
        MD5(
          COALESCE(CAST(IFF((LKP_RPT_GRPLVL_1_VAL_TX IS NULL), ' ', LKP_RPT_GRPLVL_1_VAL_TX) AS VARCHAR), '') || 
          COALESCE(CAST(IFF((LKP_RPT_GRPLVL_2_VAL_TX IS NULL), ' ', LKP_RPT_GRPLVL_2_VAL_TX) AS VARCHAR), '') || 
          COALESCE(CAST(IFF((LKP_RPT_GRPLVL_3_VAL_TX IS NULL), ' ', LKP_RPT_GRPLVL_3_VAL_TX) AS VARCHAR), '') || 
          COALESCE(CAST(IFF((LKP_RPT_GRPLVL_4_VAL_TX IS NULL), ' ', LKP_RPT_GRPLVL_4_VAL_TX) AS VARCHAR), '')
        ) AS LKP_CHECKSUM,
        MD5(
          COALESCE(CAST(IFF((RPT_GRPLVL_1_VAL_TX IS NULL), ' ', RPT_GRPLVL_1_VAL_TX) AS VARCHAR), '') || 
          COALESCE(CAST(IFF((RPT_GRPLVL_2_VAL_TX IS NULL), ' ', RPT_GRPLVL_2_VAL_TX) AS VARCHAR), '') || 
          COALESCE(CAST(IFF((RPT_GRPLVL_3_VAL_TX IS NULL), ' ', RPT_GRPLVL_3_VAL_TX) AS VARCHAR), '') || 
          COALESCE(CAST(IFF((RPT_GRPLVL_4_VAL_TX IS NULL), ' ', RPT_GRPLVL_4_VAL_TX) AS VARCHAR), '')
        ) AS SRC_CHECKSUM,
        CASE
          HRCHY_LVL_2_TX
          WHEN 'AEP Corporate' THEN 'Corp/Shared Services'
          WHEN 'AEP External Affairs' THEN 'Corp/Shared Services'
          WHEN 'Chief Administrative Office' THEN 'Corp/Shared Services'
          WHEN 'Chief Info & Tech Officer' THEN 'Corp/Shared Services'
          WHEN 'Energy Supply' THEN 'Corp/Shared Services'
          ELSE HRCHY_LVL_2_TX
        END AS SRC_BUSINESS_UNIT_GRP,
        'Y' AS O_ACTIVE_FLAG,
        CURRENT_TIMESTAMP() AS O_START_DATE,
        TRY_TO_DATE('12-31-9999', 'MM-DD-YYYY') AS O_END_DATE,
        'SHMSUSER' AS EDW_LAST_UPDT_USERID,
        CURRENT_TIMESTAMP() AS EDW_LAST_UPDT_TS
      FROM
        SQ_ODS_SHMS_LOC_ENTTY
        LEFT JOIN LKPTRANS lkp_LKPTRANS ON lkp_LKPTRANS.LKP_LOC_CD = SQ_ODS_SHMS_LOC_ENTTY.LOC_CD
),
EXPTRANS AS (
  SELECT
        EXPTRANS_step1.*,
        IFF(
          (LKP_RPRTNG_ID IS NULL),
          'I',
          IFF(
            NOT ((LKP_RPRTNG_ID IS NULL)) AND SRC_CHECKSUM <> LKP_CHECKSUM,
            'U',
            NULL
          )
        ) AS FLAG
      FROM EXPTRANS_step1
),
RTRTRANS_INSERT AS (
  SELECT
      EXPTRANS.LOC_CD,
      EXPTRANS.RPT_GRPLVL_1_VAL_TX,
      EXPTRANS.RPT_GRPLVL_2_VAL_TX,
      EXPTRANS.RPT_GRPLVL_3_VAL_TX,
      EXPTRANS.RPT_GRPLVL_4_VAL_TX,
      EXPTRANS.HRCHY_LVL_2_TX,
      EXPTRANS.LKP_CHECKSUM,
      EXPTRANS.SRC_CHECKSUM,
      EXPTRANS.SRC_BUSINESS_UNIT_GRP,
      EXPTRANS.FLAG,
      EXPTRANS.O_ACTIVE_FLAG,
      EXPTRANS.O_START_DATE,
      EXPTRANS.O_END_DATE,
      EXPTRANS.EDW_LAST_UPDT_USERID,
      EXPTRANS.EDW_LAST_UPDT_TS
    FROM EXPTRANS
    WHERE FLAG = 'I'
),
RTRTRANS_INSERT_UPDATE AS (
  SELECT
        EXPTRANS.LOC_CD,
        EXPTRANS.RPT_GRPLVL_1_VAL_TX,
        EXPTRANS.RPT_GRPLVL_2_VAL_TX,
        EXPTRANS.RPT_GRPLVL_3_VAL_TX,
        EXPTRANS.RPT_GRPLVL_4_VAL_TX,
        EXPTRANS.HRCHY_LVL_2_TX,
        EXPTRANS.LKP_CHECKSUM,
        EXPTRANS.SRC_CHECKSUM,
        EXPTRANS.SRC_BUSINESS_UNIT_GRP,
        EXPTRANS.FLAG,
        EXPTRANS.O_ACTIVE_FLAG,
        EXPTRANS.O_START_DATE,
        EXPTRANS.O_END_DATE,
        EXPTRANS.EDW_LAST_UPDT_USERID,
        EXPTRANS.EDW_LAST_UPDT_TS
      FROM EXPTRANS
      WHERE FLAG = 'U'
),
EXPTRANS1 AS (
  SELECT RTRTRANS_INSERT_UPDATE.*
      FROM RTRTRANS_INSERT_UPDATE
),
UPDTRANS2 AS (
  SELECT
        EXPTRANS1.LOC_CD,
        EXPTRANS1.RPT_GRPLVL_1_VAL_TX,
        EXPTRANS1.RPT_GRPLVL_2_VAL_TX,
        EXPTRANS1.RPT_GRPLVL_3_VAL_TX,
        EXPTRANS1.RPT_GRPLVL_4_VAL_TX,
        EXPTRANS1.HRCHY_LVL_2_TX,
        EXPTRANS1.LKP_CHECKSUM,
        EXPTRANS1.SRC_CHECKSUM,
        EXPTRANS1.SRC_BUSINESS_UNIT_GRP,
        EXPTRANS1.FLAG,
        EXPTRANS1.O_ACTIVE_FLAG,
        EXPTRANS1.O_START_DATE,
        EXPTRANS1.O_END_DATE,
        EXPTRANS1.EDW_LAST_UPDT_USERID,
        EXPTRANS1.EDW_LAST_UPDT_TS,
        0 AS DML_FLAG
      FROM EXPTRANS1
)

SELECT
    CAST(NULL AS VARCHAR(200)) AS RPRTNG_ID,  -- not in split CTE, no default
    CAST(LEFT(TRIM(COALESCE(TGT.RPT_GRPLVL_1_VAL_TX, SRC.RPT_GRPLVL_1_VAL_TX)), 200) AS VARCHAR(200)) AS RPT_GRPLVL_1_VAL_TX,
    CAST(LEFT(TRIM(COALESCE(TGT.RPT_GRPLVL_2_VAL_TX, SRC.RPT_GRPLVL_2_VAL_TX)), 200) AS VARCHAR(200)) AS RPT_GRPLVL_2_VAL_TX,
    CAST(LEFT(TRIM(COALESCE(TGT.RPT_GRPLVL_3_VAL_TX, SRC.RPT_GRPLVL_3_VAL_TX)), 200) AS VARCHAR(200)) AS RPT_GRPLVL_3_VAL_TX,
    CAST(LEFT(TRIM(COALESCE(TGT.RPT_GRPLVL_4_VAL_TX, SRC.RPT_GRPLVL_4_VAL_TX)), 200) AS VARCHAR(200)) AS RPT_GRPLVL_4_VAL_TX,
    CAST(LEFT(TRIM(COALESCE(TGT.LOC_CD, SRC.LOC_CD)), 200) AS VARCHAR(200)) AS LOC_CD,
    CAST(NULL AS TIMESTAMP_NTZ(9)) AS EFFCT_STRT_DT,  -- not in split CTE, no default
    CAST(NULL AS TIMESTAMP_NTZ(9)) AS EFFCT_END_DT,  -- not in split CTE, no default
    CAST(NULL AS VARCHAR(1)) AS ACTIVE_FLAG,  -- not in split CTE, no default
    CAST(NULL AS VARCHAR(10)) AS EDW_LAST_UPDT_USER_ID,  -- not in split CTE, no default
    CAST(TRIM(SRC.EDW_LAST_UPDT_TS) AS TIMESTAMP_NTZ(6)) AS EDW_LAST_UPDT_TS,
    CAST(NULL AS VARCHAR(200)) AS BUSINESS_UNIT_GRP  -- not in split CTE, no default

FROM
    UPDTRANS2 SRC
LEFT JOIN
    {{this}} TGT
ON
    SRC.RPRTNG_ID = TGT.RPRTNG_ID
WHERE
  (
   DECODE(CAST(LEFT(TRIM(tgt.ACTIVE_FLAG), 1) AS VARCHAR(1)), CAST(LEFT(TRIM(src.ACTIVE_FLAG), 1) AS VARCHAR(1)), 1, 0) = 0 OR  -- missing in split CTE
   DECODE(CAST(TRIM(tgt.EFFCT_END_DT) AS TIMESTAMP_NTZ(9)), CAST(TRIM(src.EFFCT_END_DT) AS TIMESTAMP_NTZ(9)), 1, 0) = 0 OR  -- missing in split CTE
   DECODE(CAST(LEFT(TRIM(tgt.EDW_LAST_UPDT_USER_ID), 10) AS VARCHAR(10)), CAST(LEFT(TRIM(src.EDW_LAST_UPDT_USER_ID), 10) AS VARCHAR(10)), 1, 0) = 0  -- missing in split CTE
   --DECODE(CAST(TRIM(tgt.EDW_LAST_UPDT_TS) AS TIMESTAMP_NTZ(6)), CAST(TRIM(src.EDW_LAST_UPDT_TS) AS TIMESTAMP_NTZ(6)), 1, 0) = 0  -- AUDIT COLUMN, MAY NOT BE NEEDED - PLEASE VERIFY
  )
