{{ config(
    materialized='incremental',
    unique_key='RPRTNG_ID',
    incremental_strategy='merge',
    full_refresh=false,
    pre_hook=[
        log_model_start(this, '/* TODO: set $AUTOSYS_JOB_NAME */')
    ],
    post_hook=[
        log_model_end(this, '/* TODO: set $AUTOSYS_JOB_NAME */')
    ]
) }}

WITH
JOB_PARAM AS (
    SELECT PARAM_ID, PARAM_NAME, PARAM_VALUE FROM {{source('CRPDB01_METADATA','SHMSADM_JOB_PARAMETERS')}}
    WHERE JOB_NAME= 'SHEMS_RPRTNG_GRP_DIM' AND AUTOSYS_JOB_NAME = '/* TODO: set $AUTOSYS_JOB_NAME */' AND ACTIVE_IND = 'Y'
),

JOB_CONTROL AS (
    SELECT JOB_ID, START_DATE, END_DATE FROM {{source('CRPDB01_METADATA','SHMSADM_JOB_CONTROL')}}
    WHERE JOB_NAME= 'SHEMS_RPRTNG_GRP_DIM' AND AUTOSYS_JOB_NAME = '/* TODO: set $AUTOSYS_JOB_NAME */'
),
CURRENT_DIM AS (
    {% if is_incremental() %}
    SELECT
        RPRTNG_ID,
        LOC_CD,
        RPT_GRPLVL_1_VAL_TX,
        RPT_GRPLVL_2_VAL_TX,
        RPT_GRPLVL_3_VAL_TX,
        RPT_GRPLVL_4_VAL_TX,
        BUSINESS_UNIT_GRP
    FROM {{this}}
    {% else %}
    SELECT
        CAST(NULL AS NUMBER(20,0)) AS RPRTNG_ID,
        CAST(NULL AS VARCHAR(20)) AS LOC_CD,
        CAST(NULL AS VARCHAR(255)) AS RPT_GRPLVL_1_VAL_TX,
        CAST(NULL AS VARCHAR(255)) AS RPT_GRPLVL_2_VAL_TX,
        CAST(NULL AS VARCHAR(255)) AS RPT_GRPLVL_3_VAL_TX,
        CAST(NULL AS VARCHAR(255)) AS RPT_GRPLVL_4_VAL_TX,
        CAST(NULL AS VARCHAR(255)) AS BUSINESS_UNIT_GRP
    WHERE 1 = 0
    {% endif %}
),
SQ_ODS_SHMS_LOC_ENTTY AS (
  SELECT
        A.LOC_CD,
        A.RPT_GRPLVL_1_VAL_TX,
        A.RPT_GRPLVL_2_VAL_TX,
        A.RPT_GRPLVL_3_VAL_TX,
        A.RPT_GRPLVL_4_VAL_TX,
        A.HRCHY_LVL_2_TX
      FROM
        {{source('CRPDB01_COMMON','ODS_SHMS_LOC_ENTTY_TEST')}} A  --CRPDB01_DEV_SANDBOX.COMMON.ODS_SHMS_LOC_ENTTY_TEST
      WHERE
        A.RPT_GRPLVL_1_VAL_TX NOT IN('na')
),
LKPTRANS AS (
  SELECT
        SQ_ODS_SHMS_LOC_ENTTY.*,
        _lkp_LKPTRANS.LKP_RPRTNG_ID,
        _lkp_LKPTRANS.LKP_RPT_GRPLVL_1_VAL_TX,
        _lkp_LKPTRANS.LKP_RPT_GRPLVL_2_VAL_TX,
        _lkp_LKPTRANS.LKP_RPT_GRPLVL_3_VAL_TX,
        _lkp_LKPTRANS.LKP_RPT_GRPLVL_4_VAL_TX,
        _lkp_LKPTRANS.LKP_LOC_CD,
        SQ_ODS_SHMS_LOC_ENTTY.LOC_CD AS SRC_LOC_CD,
        _lkp_LKPTRANS.LKP_BUSINESS_UNIT_GRP
      FROM
        SQ_ODS_SHMS_LOC_ENTTY
        LEFT JOIN (
          SELECT
            DIM.RPRTNG_ID as LKP_RPRTNG_ID,
            DIM.LOC_CD as LKP_LOC_CD,
            DIM.RPT_GRPLVL_1_VAL_TX as LKP_RPT_GRPLVL_1_VAL_TX,
            DIM.RPT_GRPLVL_2_VAL_TX as LKP_RPT_GRPLVL_2_VAL_TX,
            DIM.RPT_GRPLVL_3_VAL_TX as LKP_RPT_GRPLVL_3_VAL_TX,
            DIM.RPT_GRPLVL_4_VAL_TX as LKP_RPT_GRPLVL_4_VAL_TX,
            DIM.BUSINESS_UNIT_GRP as LKP_BUSINESS_UNIT_GRP
          FROM
            CURRENT_DIM DIM  --CRPDB01_DEV_SANDBOX.SHMSADM.SHEMS_RPRTNG_GRP_DIM
        ) _lkp_LKPTRANS ON _lkp_LKPTRANS.LKP_LOC_CD = SQ_ODS_SHMS_LOC_ENTTY.LOC_CD
),
EXPTRANS_step1 AS (
  SELECT
        SQ_ODS_SHMS_LOC_ENTTY.*,
        lkp_LKPTRANS.LKP_RPRTNG_ID,
        lkp_LKPTRANS.LKP_RPT_GRPLVL_1_VAL_TX,
        lkp_LKPTRANS.LKP_RPT_GRPLVL_2_VAL_TX,
        lkp_LKPTRANS.LKP_RPT_GRPLVL_3_VAL_TX,
        lkp_LKPTRANS.LKP_RPT_GRPLVL_4_VAL_TX,
        lkp_LKPTRANS.LKP_LOC_CD,
        lkp_LKPTRANS.LKP_BUSINESS_UNIT_GRP,
        MD5(
          COALESCE(CAST(IFF((lkp_LKPTRANS.LKP_RPT_GRPLVL_1_VAL_TX IS NULL), ' ', lkp_LKPTRANS.LKP_RPT_GRPLVL_1_VAL_TX) AS VARCHAR), '') || 
          COALESCE(CAST(IFF((lkp_LKPTRANS.LKP_RPT_GRPLVL_2_VAL_TX IS NULL), ' ', lkp_LKPTRANS.LKP_RPT_GRPLVL_2_VAL_TX) AS VARCHAR), '') || 
          COALESCE(CAST(IFF((lkp_LKPTRANS.LKP_RPT_GRPLVL_3_VAL_TX IS NULL), ' ', lkp_LKPTRANS.LKP_RPT_GRPLVL_3_VAL_TX) AS VARCHAR), '') || 
          COALESCE(CAST(IFF((lkp_LKPTRANS.LKP_RPT_GRPLVL_4_VAL_TX IS NULL), ' ', lkp_LKPTRANS.LKP_RPT_GRPLVL_4_VAL_TX) AS VARCHAR), '')
        ) AS LKP_CHECKSUM,
        MD5(
          COALESCE(CAST(IFF((SQ_ODS_SHMS_LOC_ENTTY.RPT_GRPLVL_1_VAL_TX IS NULL), ' ', SQ_ODS_SHMS_LOC_ENTTY.RPT_GRPLVL_1_VAL_TX) AS VARCHAR), '') || 
          COALESCE(CAST(IFF((SQ_ODS_SHMS_LOC_ENTTY.RPT_GRPLVL_2_VAL_TX IS NULL), ' ', SQ_ODS_SHMS_LOC_ENTTY.RPT_GRPLVL_2_VAL_TX) AS VARCHAR), '') || 
          COALESCE(CAST(IFF((SQ_ODS_SHMS_LOC_ENTTY.RPT_GRPLVL_3_VAL_TX IS NULL), ' ', SQ_ODS_SHMS_LOC_ENTTY.RPT_GRPLVL_3_VAL_TX) AS VARCHAR), '') || 
          COALESCE(CAST(IFF((SQ_ODS_SHMS_LOC_ENTTY.RPT_GRPLVL_4_VAL_TX IS NULL), ' ', SQ_ODS_SHMS_LOC_ENTTY.RPT_GRPLVL_4_VAL_TX) AS VARCHAR), '')
        ) AS SRC_CHECKSUM,
        CASE
          SQ_ODS_SHMS_LOC_ENTTY.HRCHY_LVL_2_TX
          WHEN 'AEP Corporate' THEN 'Corp/Shared Services'
          WHEN 'AEP External Affairs' THEN 'Corp/Shared Services'
          WHEN 'Chief Administrative Office' THEN 'Corp/Shared Services'
          WHEN 'Chief Info & Tech Officer' THEN 'Corp/Shared Services'
          WHEN 'Energy Supply' THEN 'Corp/Shared Services'
          ELSE SQ_ODS_SHMS_LOC_ENTTY.HRCHY_LVL_2_TX
        END AS SRC_BUSINESS_UNIT_GRP,
        'Y' AS O_ACTIVE_FLAG,
        CURRENT_TIMESTAMP() AS O_START_DATE,
        TRY_TO_DATE('12-31-9999', 'MM-DD-YYYY') AS O_END_DATE,
        'SHMSUSER' AS EDW_LAST_UPDT_USERID,
        CURRENT_TIMESTAMP() AS EDW_LAST_UPDT_TS
      FROM
        SQ_ODS_SHMS_LOC_ENTTY
        LEFT JOIN LKPTRANS lkp_LKPTRANS ON lkp_LKPTRANS.LKP_LOC_CD = SQ_ODS_SHMS_LOC_ENTTY.LOC_CD
),
EXPTRANS AS (
  SELECT
        EXPTRANS_step1.*,
        IFF(
          (LKP_RPRTNG_ID IS NULL),
          'I',
          IFF(
            NOT ((LKP_RPRTNG_ID IS NULL)) AND SRC_CHECKSUM <> LKP_CHECKSUM,
            'U',
            NULL
          )
        ) AS FLAG
      FROM EXPTRANS_step1
),
RTRTRANS_INSERT AS (
  SELECT
      EXPTRANS.LOC_CD,
      EXPTRANS.RPT_GRPLVL_1_VAL_TX,
      EXPTRANS.RPT_GRPLVL_2_VAL_TX,
      EXPTRANS.RPT_GRPLVL_3_VAL_TX,
      EXPTRANS.RPT_GRPLVL_4_VAL_TX,
      EXPTRANS.HRCHY_LVL_2_TX,
      EXPTRANS.LKP_CHECKSUM,
      EXPTRANS.SRC_CHECKSUM,
      EXPTRANS.SRC_BUSINESS_UNIT_GRP,
      EXPTRANS.FLAG,
      EXPTRANS.O_ACTIVE_FLAG,
      EXPTRANS.O_START_DATE,
      EXPTRANS.O_END_DATE,
      EXPTRANS.EDW_LAST_UPDT_USERID,
      EXPTRANS.EDW_LAST_UPDT_TS
    FROM EXPTRANS
    WHERE FLAG = 'I'
),
RTRTRANS_INSERT_UPDATE AS (
  SELECT
        EXPTRANS.LOC_CD,
        EXPTRANS.RPT_GRPLVL_1_VAL_TX,
        EXPTRANS.RPT_GRPLVL_2_VAL_TX,
        EXPTRANS.RPT_GRPLVL_3_VAL_TX,
        EXPTRANS.RPT_GRPLVL_4_VAL_TX,
        EXPTRANS.HRCHY_LVL_2_TX,
        EXPTRANS.LKP_CHECKSUM,
        EXPTRANS.SRC_CHECKSUM,
        EXPTRANS.SRC_BUSINESS_UNIT_GRP,
        EXPTRANS.FLAG,
        EXPTRANS.O_ACTIVE_FLAG,
        EXPTRANS.O_START_DATE,
        EXPTRANS.O_END_DATE,
        EXPTRANS.EDW_LAST_UPDT_USERID,
        EXPTRANS.EDW_LAST_UPDT_TS
      FROM EXPTRANS
      WHERE FLAG = 'U'
),
EXPTRANS1 AS (
  SELECT RTRTRANS_INSERT_UPDATE.*
      FROM RTRTRANS_INSERT_UPDATE
),
UPDTRANS2 AS (
  SELECT
        EXPTRANS1.LOC_CD,
        EXPTRANS1.RPT_GRPLVL_1_VAL_TX,
        EXPTRANS1.RPT_GRPLVL_2_VAL_TX,
        EXPTRANS1.RPT_GRPLVL_3_VAL_TX,
        EXPTRANS1.RPT_GRPLVL_4_VAL_TX,
        EXPTRANS1.HRCHY_LVL_2_TX,
        EXPTRANS1.LKP_CHECKSUM,
        EXPTRANS1.SRC_CHECKSUM,
        EXPTRANS1.SRC_BUSINESS_UNIT_GRP,
        EXPTRANS1.FLAG,
        EXPTRANS1.O_ACTIVE_FLAG,
        EXPTRANS1.O_START_DATE,
        EXPTRANS1.O_END_DATE,
        EXPTRANS1.EDW_LAST_UPDT_USERID,
        EXPTRANS1.EDW_LAST_UPDT_TS,
        0 AS DML_FLAG
      FROM EXPTRANS1
),
FINAL_ROWS AS (
  SELECT
        RTRTRANS_INSERT.LOC_CD,
        RTRTRANS_INSERT.RPT_GRPLVL_1_VAL_TX,
        RTRTRANS_INSERT.RPT_GRPLVL_2_VAL_TX,
        RTRTRANS_INSERT.RPT_GRPLVL_3_VAL_TX,
        RTRTRANS_INSERT.RPT_GRPLVL_4_VAL_TX,
        RTRTRANS_INSERT.O_ACTIVE_FLAG,
        RTRTRANS_INSERT.O_START_DATE,
        RTRTRANS_INSERT.O_END_DATE,
        RTRTRANS_INSERT.EDW_LAST_UPDT_USERID,
        RTRTRANS_INSERT.EDW_LAST_UPDT_TS,
        RTRTRANS_INSERT.SRC_BUSINESS_UNIT_GRP,
        0 AS DML_FLAG
      FROM RTRTRANS_INSERT
  UNION ALL
  SELECT
        UPDTRANS2.LOC_CD,
        UPDTRANS2.RPT_GRPLVL_1_VAL_TX,
        UPDTRANS2.RPT_GRPLVL_2_VAL_TX,
        UPDTRANS2.RPT_GRPLVL_3_VAL_TX,
        UPDTRANS2.RPT_GRPLVL_4_VAL_TX,
        UPDTRANS2.O_ACTIVE_FLAG,
        UPDTRANS2.O_START_DATE,
        UPDTRANS2.O_END_DATE,
        UPDTRANS2.EDW_LAST_UPDT_USERID,
        UPDTRANS2.EDW_LAST_UPDT_TS,
        UPDTRANS2.SRC_BUSINESS_UNIT_GRP,
        UPDTRANS2.DML_FLAG
      FROM UPDTRANS2
)

SELECT
    COALESCE((SELECT MAX(RPRTNG_ID) FROM CURRENT_DIM), 0) + ROW_NUMBER() OVER (ORDER BY LOC_CD) AS RPRTNG_ID,
    CAST(LEFT(TRIM(O_ACTIVE_FLAG), 1) AS VARCHAR(1)) AS ACTIVE_FLAG,
    CAST(O_START_DATE AS TIMESTAMP_NTZ(6)) AS EFFCT_STRT_DT,
    CAST(O_END_DATE AS DATE) AS EFFCT_END_DT,
    CAST(LEFT(TRIM(EDW_LAST_UPDT_USERID), 20) AS VARCHAR(20)) AS EDW_LAST_UPDT_USER_ID,
    CAST(EDW_LAST_UPDT_TS AS TIMESTAMP_NTZ(6)) AS EDW_LAST_UPDT_TS,
    CAST(LEFT(TRIM(LOC_CD), 20) AS VARCHAR(20)) AS LOC_CD,
    CAST(LEFT(TRIM(RPT_GRPLVL_1_VAL_TX), 255) AS VARCHAR(255)) AS RPT_GRPLVL_1_VAL_TX,
    CAST(LEFT(TRIM(RPT_GRPLVL_2_VAL_TX), 255) AS VARCHAR(255)) AS RPT_GRPLVL_2_VAL_TX,
    CAST(LEFT(TRIM(RPT_GRPLVL_3_VAL_TX), 255) AS VARCHAR(255)) AS RPT_GRPLVL_3_VAL_TX,
    CAST(LEFT(TRIM(RPT_GRPLVL_4_VAL_TX), 255) AS VARCHAR(255)) AS RPT_GRPLVL_4_VAL_TX,
    CAST(LEFT(TRIM(SRC_BUSINESS_UNIT_GRP), 255) AS VARCHAR(255)) AS BUSINESS_UNIT_GRP
FROM FINAL_ROWS
WHERE DML_FLAG = 0
