-- =============================================================================
-- Mapping: m_shems_rprtng_grp_dim_ins_upd
-- Source: Informatica converted to SQL
-- Corrected converter input: mapping behaves as truncate/load.
-- =============================================================================

$TYPE: TRUNCATE, INSERT

$TARGET_TABLE: CRPDB01_DEV_SANDBOX.SHMSADM.SHEMS_RPRTNG_GRP_DIM

$TARGET_TABLE_COLUMNS: RPRTNG_ID, ACTIVE_FLAG, EFFCT_STRT_DT, EFFCT_END_DT, EDW_LAST_UPDT_USER_ID, EDW_LAST_UPDT_TS, LOC_CD, RPT_GRPLVL_1_VAL_TX, RPT_GRPLVL_2_VAL_TX, RPT_GRPLVL_3_VAL_TX, RPT_GRPLVL_4_VAL_TX, BUSINESS_UNIT_GRP

$PRIMARY_KEY: RPRTNG_ID

$UPDATE_COLUMNS: NONE

$SPLIT_CTE: FINAL_ROWS

$AUTOSYS_JOB_NAME: SHEMS_RPRTNG_GRP_DIM_LOAD

$SOURCE_CODE:
WITH SQ_ODS_SHMS_LOC_ENTTY AS (
    SELECT
      A.LOC_CD,
      A.RPT_GRPLVL_1_VAL_TX,
      A.RPT_GRPLVL_2_VAL_TX,
      A.RPT_GRPLVL_3_VAL_TX,
      A.RPT_GRPLVL_4_VAL_TX,
      A.HRCHY_LVL_2_TX
    FROM
      CRPDB01_DEV_SANDBOX.COMMON.ODS_SHMS_LOC_ENTTY_TEST A
    WHERE
      A.RPT_GRPLVL_1_VAL_TX NOT IN ('na')
),
EXPTRANS AS (
    SELECT
      LOC_CD,
      RPT_GRPLVL_1_VAL_TX,
      RPT_GRPLVL_2_VAL_TX,
      RPT_GRPLVL_3_VAL_TX,
      RPT_GRPLVL_4_VAL_TX,
      CASE
        HRCHY_LVL_2_TX
        WHEN 'AEP Corporate' THEN 'Corp/Shared Services'
        WHEN 'AEP External Affairs' THEN 'Corp/Shared Services'
        WHEN 'Chief Administrative Office' THEN 'Corp/Shared Services'
        WHEN 'Chief Info & Tech Officer' THEN 'Corp/Shared Services'
        WHEN 'Energy Supply' THEN 'Corp/Shared Services'
        ELSE HRCHY_LVL_2_TX
      END AS BUSINESS_UNIT_GRP,
      'Y' AS ACTIVE_FLAG,
      CURRENT_TIMESTAMP() AS EFFCT_STRT_DT,
      TRY_TO_DATE('12-31-9999', 'MM-DD-YYYY') AS EFFCT_END_DT,
      'SHMSUSER' AS EDW_LAST_UPDT_USER_ID,
      CURRENT_TIMESTAMP() AS EDW_LAST_UPDT_TS
    FROM SQ_ODS_SHMS_LOC_ENTTY
),
FINAL_ROWS AS (
    SELECT
      ROW_NUMBER() OVER (ORDER BY LOC_CD) AS RPRTNG_ID,
      ACTIVE_FLAG,
      EFFCT_STRT_DT,
      EFFCT_END_DT,
      EDW_LAST_UPDT_USER_ID,
      EDW_LAST_UPDT_TS,
      LOC_CD,
      RPT_GRPLVL_1_VAL_TX,
      RPT_GRPLVL_2_VAL_TX,
      RPT_GRPLVL_3_VAL_TX,
      RPT_GRPLVL_4_VAL_TX,
      BUSINESS_UNIT_GRP
    FROM EXPTRANS
)
SELECT
  RPRTNG_ID,
  ACTIVE_FLAG,
  EFFCT_STRT_DT,
  EFFCT_END_DT,
  EDW_LAST_UPDT_USER_ID,
  EDW_LAST_UPDT_TS,
  LOC_CD,
  RPT_GRPLVL_1_VAL_TX,
  RPT_GRPLVL_2_VAL_TX,
  RPT_GRPLVL_3_VAL_TX,
  RPT_GRPLVL_4_VAL_TX,
  BUSINESS_UNIT_GRP
FROM FINAL_ROWS;

$DESC_TABLE:
name	type	kind	null?	default
RPRTNG_ID	NUMBER(20,0)	COLUMN	N	
ACTIVE_FLAG	VARCHAR(1)	COLUMN	Y	
EFFCT_STRT_DT	TIMESTAMP_NTZ(6)	COLUMN	Y	
EFFCT_END_DT	DATE	COLUMN	Y	
EDW_LAST_UPDT_USER_ID	VARCHAR(20)	COLUMN	Y	
EDW_LAST_UPDT_TS	TIMESTAMP_NTZ(6)	COLUMN	Y	
LOC_CD	VARCHAR(20)	COLUMN	Y	
RPT_GRPLVL_1_VAL_TX	VARCHAR(255)	COLUMN	Y	
RPT_GRPLVL_2_VAL_TX	VARCHAR(255)	COLUMN	Y	
RPT_GRPLVL_3_VAL_TX	VARCHAR(255)	COLUMN	Y	
RPT_GRPLVL_4_VAL_TX	VARCHAR(255)	COLUMN	Y	
BUSINESS_UNIT_GRP	VARCHAR(255)	COLUMN	Y	
