-- =============================================================================
-- Mapping: m_shems_rprtng_grp_dim_ins_upd
-- Source: Informatica converted to SQL
-- =============================================================================

$TYPE: INSERT, UPDATE

$TARGET_TABLE: CRPDB01_DEV_SANDBOX.SHMSADM.SHEMS_RPRTNG_GRP_DIM

$TARGET_TABLE_COLUMNS: RPRTNG_ID, ACTIVE_FLAG, EFFCT_STRT_DT, EFFCT_END_DT, EDW_LAST_UPDT_USER_ID, EDW_LAST_UPDT_TS, LOC_CD, RPT_GRPLVL_1_VAL_TX, RPT_GRPLVL_2_VAL_TX, RPT_GRPLVL_3_VAL_TX, RPT_GRPLVL_4_VAL_TX, BUSINESS_UNIT_GRP

$PRIMARY_KEY: RPRTNG_ID

$UPDATE_COLUMNS:
TGT.ACTIVE_FLAG = SRC.ACTIVE_FLAG,
TGT.EFFCT_END_DT = SRC.EFFCT_END_DT,
TGT.EDW_LAST_UPDT_USER_ID = SRC.EDW_LAST_UPDT_USER_ID,
TGT.EDW_LAST_UPDT_TS = SRC.EDW_LAST_UPDT_TS

$SPLIT_CTE: UPDTRANS2

$AUTOSYS_JOB_NAME: SHEMS_RPRTNG_GRP_DIM_LOAD


$SOURCE_CODE:
WITH SQ_ODS_SHMS_LOC_ENTTY AS (
    SELECT
      A.LOC_CD,
      A.RPT_GRPLVL_1_VAL_TX,
      A.RPT_GRPLVL_2_VAL_TX,
      A.RPT_GRPLVL_3_VAL_TX,
      A.RPT_GRPLVL_4_VAL_TX,
      A.HRCHY_LVL_2_TX
    FROM
      CRPDB01_DEV_SANDBOX.COMMON.ODS_SHMS_LOC_ENTTY_TEST A
    WHERE
      A.RPT_GRPLVL_1_VAL_TX NOT IN('na')
),
LKPTRANS AS (
    SELECT
      SQ_ODS_SHMS_LOC_ENTTY.*,
      _lkp_LKPTRANS.LKP_RPRTNG_ID,
      _lkp_LKPTRANS.LKP_RPT_GRPLVL_1_VAL_TX,
      _lkp_LKPTRANS.LKP_RPT_GRPLVL_2_VAL_TX,
      _lkp_LKPTRANS.LKP_RPT_GRPLVL_3_VAL_TX,
      _lkp_LKPTRANS.LKP_RPT_GRPLVL_4_VAL_TX,
      _lkp_LKPTRANS.LKP_LOC_CD,
      SQ_ODS_SHMS_LOC_ENTTY.LOC_CD AS SRC_LOC_CD,
      _lkp_LKPTRANS.LKP_BUSINESS_UNIT_GRP
    FROM
      SQ_ODS_SHMS_LOC_ENTTY
      LEFT JOIN (
        SELECT
          DIM.RPRTNG_ID as LKP_RPRTNG_ID,
          DIM.LOC_CD as LKP_LOC_CD,
          DIM.RPT_GRPLVL_1_VAL_TX as LKP_RPT_GRPLVL_1_VAL_TX,
          DIM.RPT_GRPLVL_2_VAL_TX as LKP_RPT_GRPLVL_2_VAL_TX,
          DIM.RPT_GRPLVL_3_VAL_TX as LKP_RPT_GRPLVL_3_VAL_TX,
          DIM.RPT_GRPLVL_4_VAL_TX as LKP_RPT_GRPLVL_4_VAL_TX,
          DIM.BUSINESS_UNIT_GRP as LKP_BUSINESS_UNIT_GRP
        FROM
          CRPDB01_DEV_SANDBOX.SHMSADM.SHEMS_RPRTNG_GRP_DIM DIM
      ) _lkp_LKPTRANS ON _lkp_LKPTRANS.LKP_LOC_CD = SQ_ODS_SHMS_LOC_ENTTY.LOC_CD
),
EXPTRANS_step1 AS (
    SELECT
      SQ_ODS_SHMS_LOC_ENTTY.*,
      lkp_LKPTRANS.LKP_RPRTNG_ID,
      lkp_LKPTRANS.LKP_RPT_GRPLVL_1_VAL_TX,
      lkp_LKPTRANS.LKP_RPT_GRPLVL_2_VAL_TX,
      lkp_LKPTRANS.LKP_RPT_GRPLVL_3_VAL_TX,
      lkp_LKPTRANS.LKP_RPT_GRPLVL_4_VAL_TX,
      lkp_LKPTRANS.LKP_LOC_CD,
      lkp_LKPTRANS.LKP_BUSINESS_UNIT_GRP,
      MD5(
        COALESCE(CAST(IFF((LKP_RPT_GRPLVL_1_VAL_TX IS NULL), ' ', LKP_RPT_GRPLVL_1_VAL_TX) AS VARCHAR), '') || 
        COALESCE(CAST(IFF((LKP_RPT_GRPLVL_2_VAL_TX IS NULL), ' ', LKP_RPT_GRPLVL_2_VAL_TX) AS VARCHAR), '') || 
        COALESCE(CAST(IFF((LKP_RPT_GRPLVL_3_VAL_TX IS NULL), ' ', LKP_RPT_GRPLVL_3_VAL_TX) AS VARCHAR), '') || 
        COALESCE(CAST(IFF((LKP_RPT_GRPLVL_4_VAL_TX IS NULL), ' ', LKP_RPT_GRPLVL_4_VAL_TX) AS VARCHAR), '')
      ) AS LKP_CHECKSUM,
      MD5(
        COALESCE(CAST(IFF((RPT_GRPLVL_1_VAL_TX IS NULL), ' ', RPT_GRPLVL_1_VAL_TX) AS VARCHAR), '') || 
        COALESCE(CAST(IFF((RPT_GRPLVL_2_VAL_TX IS NULL), ' ', RPT_GRPLVL_2_VAL_TX) AS VARCHAR), '') || 
        COALESCE(CAST(IFF((RPT_GRPLVL_3_VAL_TX IS NULL), ' ', RPT_GRPLVL_3_VAL_TX) AS VARCHAR), '') || 
        COALESCE(CAST(IFF((RPT_GRPLVL_4_VAL_TX IS NULL), ' ', RPT_GRPLVL_4_VAL_TX) AS VARCHAR), '')
      ) AS SRC_CHECKSUM,
      CASE
        HRCHY_LVL_2_TX
        WHEN 'AEP Corporate' THEN 'Corp/Shared Services'
        WHEN 'AEP External Affairs' THEN 'Corp/Shared Services'
        WHEN 'Chief Administrative Office' THEN 'Corp/Shared Services'
        WHEN 'Chief Info & Tech Officer' THEN 'Corp/Shared Services'
        WHEN 'Energy Supply' THEN 'Corp/Shared Services'
        ELSE HRCHY_LVL_2_TX
      END AS SRC_BUSINESS_UNIT_GRP,
      'Y' AS O_ACTIVE_FLAG,
      CURRENT_TIMESTAMP() AS O_START_DATE,
      TRY_TO_DATE('12-31-9999', 'MM-DD-YYYY') AS O_END_DATE,
      'SHMSUSER' AS EDW_LAST_UPDT_USERID,
      CURRENT_TIMESTAMP() AS EDW_LAST_UPDT_TS
    FROM
      SQ_ODS_SHMS_LOC_ENTTY
      LEFT JOIN LKPTRANS lkp_LKPTRANS ON lkp_LKPTRANS.LKP_LOC_CD = SQ_ODS_SHMS_LOC_ENTTY.LOC_CD
),
EXPTRANS AS (
    SELECT
      EXPTRANS_step1.*,
      IFF(
        (LKP_RPRTNG_ID IS NULL),
        'I',
        IFF(
          NOT ((LKP_RPRTNG_ID IS NULL)) AND SRC_CHECKSUM <> LKP_CHECKSUM,
          'U',
          NULL
        )
      ) AS FLAG
    FROM EXPTRANS_step1
),
RTRTRANS_INSERT AS (
  SELECT
    EXPTRANS.LOC_CD,
    EXPTRANS.RPT_GRPLVL_1_VAL_TX,
    EXPTRANS.RPT_GRPLVL_2_VAL_TX,
    EXPTRANS.RPT_GRPLVL_3_VAL_TX,
    EXPTRANS.RPT_GRPLVL_4_VAL_TX,
    EXPTRANS.HRCHY_LVL_2_TX,
    EXPTRANS.LKP_CHECKSUM,
    EXPTRANS.SRC_CHECKSUM,
    EXPTRANS.SRC_BUSINESS_UNIT_GRP,
    EXPTRANS.FLAG,
    EXPTRANS.O_ACTIVE_FLAG,
    EXPTRANS.O_START_DATE,
    EXPTRANS.O_END_DATE,
    EXPTRANS.EDW_LAST_UPDT_USERID,
    EXPTRANS.EDW_LAST_UPDT_TS
  FROM EXPTRANS
  WHERE FLAG = 'I'
),
RTRTRANS_INSERT_UPDATE AS (
    SELECT
      EXPTRANS.LOC_CD,
      EXPTRANS.RPT_GRPLVL_1_VAL_TX,
      EXPTRANS.RPT_GRPLVL_2_VAL_TX,
      EXPTRANS.RPT_GRPLVL_3_VAL_TX,
      EXPTRANS.RPT_GRPLVL_4_VAL_TX,
      EXPTRANS.HRCHY_LVL_2_TX,
      EXPTRANS.LKP_CHECKSUM,
      EXPTRANS.SRC_CHECKSUM,
      EXPTRANS.SRC_BUSINESS_UNIT_GRP,
      EXPTRANS.FLAG,
      EXPTRANS.O_ACTIVE_FLAG,
      EXPTRANS.O_START_DATE,
      EXPTRANS.O_END_DATE,
      EXPTRANS.EDW_LAST_UPDT_USERID,
      EXPTRANS.EDW_LAST_UPDT_TS
    FROM EXPTRANS
    WHERE FLAG = 'U'
),
EXPTRANS1 AS (
    SELECT RTRTRANS_INSERT_UPDATE.*
    FROM RTRTRANS_INSERT_UPDATE
),
UPDTRANS2 AS (
    SELECT
      EXPTRANS1.LOC_CD,
      EXPTRANS1.RPT_GRPLVL_1_VAL_TX,
      EXPTRANS1.RPT_GRPLVL_2_VAL_TX,
      EXPTRANS1.RPT_GRPLVL_3_VAL_TX,
      EXPTRANS1.RPT_GRPLVL_4_VAL_TX,
      EXPTRANS1.HRCHY_LVL_2_TX,
      EXPTRANS1.LKP_CHECKSUM,
      EXPTRANS1.SRC_CHECKSUM,
      EXPTRANS1.SRC_BUSINESS_UNIT_GRP,
      EXPTRANS1.FLAG,
      EXPTRANS1.O_ACTIVE_FLAG,
      EXPTRANS1.O_START_DATE,
      EXPTRANS1.O_END_DATE,
      EXPTRANS1.EDW_LAST_UPDT_USERID,
      EXPTRANS1.EDW_LAST_UPDT_TS,
      0 AS DML_FLAG
    FROM EXPTRANS1
)
SELECT
  COALESCE((SELECT MAX(RPRTNG_ID) FROM CRPDB01_DEV_SANDBOX.SHMSADM.SHEMS_RPRTNG_GRP_DIM), 0) + ROW_NUMBER() OVER (ORDER BY 1) as RPRTNG_ID,
  O_ACTIVE_FLAG AS ACTIVE_FLAG,
  O_START_DATE AS EFFCT_STRT_DT,
  O_END_DATE AS EFFCT_END_DT,
  EDW_LAST_UPDT_USERID AS EDW_LAST_UPDT_USER_ID,
  EDW_LAST_UPDT_TS,
  LOC_CD,
  RPT_GRPLVL_1_VAL_TX,
  RPT_GRPLVL_2_VAL_TX,
  RPT_GRPLVL_3_VAL_TX,
  RPT_GRPLVL_4_VAL_TX,
  SRC_BUSINESS_UNIT_GRP AS BUSINESS_UNIT_GRP
FROM UPDTRANS2
WHERE DML_FLAG = 0;

$DESC_TABLE:
name	type	kind	null?	default
RPRTNG_ID	NUMBER(20,0)	COLUMN	N	
ACTIVE_FLAG	VARCHAR(1)	COLUMN	Y	
EFFCT_STRT_DT	TIMESTAMP_NTZ(6)	COLUMN	Y	
EFFCT_END_DT	DATE	COLUMN	Y	
EDW_LAST_UPDT_USER_ID	VARCHAR(20)	COLUMN	Y	
EDW_LAST_UPDT_TS	TIMESTAMP_NTZ(6)	COLUMN	Y	
LOC_CD	VARCHAR(20)	COLUMN	Y	
RPT_GRPLVL_1_VAL_TX	VARCHAR(255)	COLUMN	Y	
RPT_GRPLVL_2_VAL_TX	VARCHAR(255)	COLUMN	Y	
RPT_GRPLVL_3_VAL_TX	VARCHAR(255)	COLUMN	Y	
RPT_GRPLVL_4_VAL_TX	VARCHAR(255)	COLUMN	Y	
BUSINESS_UNIT_GRP	VARCHAR(255)	COLUMN	Y	
