-- =============================================================================
-- Mapping: m_shems_rprtng_grp_dim_ins_upd
-- Generated by inf2snow v10.5.0
-- =============================================================================
--Flow 1 - Ins_UPD  
--Flow 2 UPDATE  
--Flow 3 INSert
--Note: SCD type-2 but on checking the session level properties it truncates and delete the target table before performing insert or update and by which we can conclude that it follows only isert flow and can be consider as truncate and load.
  --== == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == =;

---select * from CRPDB01_DEV_SANDBOX.SHMSADM.SHEMS_RPRTNG_GRP_DIM;
delete from CRPDB01_DEV_SANDBOX.SHMSADM.SHEMS_RPRTNG_GRP_DIM;


INSERT INTO
  CRPDB01_DEV_SANDBOX.SHMSADM.SHEMS_RPRTNG_GRP_DIM (
    RPRTNG_ID,
    ACTIVE_FLAG,
    EFFCT_STRT_DT,
    EFFCT_END_DT,
    EDW_LAST_UPDT_USER_ID,
    EDW_LAST_UPDT_TS,
    LOC_CD,
    RPT_GRPLVL_1_VAL_TX,
    RPT_GRPLVL_2_VAL_TX,
    RPT_GRPLVL_3_VAL_TX,
    RPT_GRPLVL_4_VAL_TX,
    BUSINESS_UNIT_GRP
  ) 
WITH SQ_ODS_SHMS_LOC_ENTTY AS (
    SELECT
      A.LOC_CD,
      A.RPT_GRPLVL_1_VAL_TX,
      A.RPT_GRPLVL_2_VAL_TX,
      A.RPT_GRPLVL_3_VAL_TX,
      A.RPT_GRPLVL_4_VAL_TX,
      A.HRCHY_LVL_2_TX
    FROM
      CRPDB01_DEV_SANDBOX.COMMON.ODS_SHMS_LOC_ENTTY_TEST A
    WHERE
      A.RPT_GRPLVL_1_VAL_TX NOT IN('na')
  ) --select * from SQ_ODS_SHMS_LOC_ENTTY;
,
  LKPTRANS AS (
    SELECT
      SQ_ODS_SHMS_LOC_ENTTY.*,
      -- EXCLUDE (LKP_BUSINESS_UNIT_GRP, LKP_LOC_CD, LKP_RPRTNG_ID, LKP_RPT_GRPLVL_1_VAL_TX, LKP_RPT_GRPLVL_2_VAL_TX, LKP_RPT_GRPLVL_3_VAL_TX, LKP_RPT_GRPLVL_4_VAL_TX, SRC_LOC_CD),
      _lkp_LKPTRANS.LKP_RPRTNG_ID,
      _lkp_LKPTRANS.LKP_RPT_GRPLVL_1_VAL_TX,
      _lkp_LKPTRANS.LKP_RPT_GRPLVL_2_VAL_TX,
      _lkp_LKPTRANS.LKP_RPT_GRPLVL_3_VAL_TX,
      _lkp_LKPTRANS.LKP_RPT_GRPLVL_4_VAL_TX,
      _lkp_LKPTRANS.LKP_LOC_CD,
      SQ_ODS_SHMS_LOC_ENTTY.LOC_CD AS SRC_LOC_CD,
      _lkp_LKPTRANS.LKP_BUSINESS_UNIT_GRP
    FROM
      SQ_ODS_SHMS_LOC_ENTTY
      LEFT JOIN (
        SELECT
          DIM.RPRTNG_ID as LKP_RPRTNG_ID,
          DIM.LOC_CD as LKP_LOC_CD,
          DIM.RPT_GRPLVL_1_VAL_TX as LKP_RPT_GRPLVL_1_VAL_TX,
          DIM.RPT_GRPLVL_2_VAL_TX as LKP_RPT_GRPLVL_2_VAL_TX,
          DIM.RPT_GRPLVL_3_VAL_TX as LKP_RPT_GRPLVL_3_VAL_TX,
          DIM.RPT_GRPLVL_4_VAL_TX as LKP_RPT_GRPLVL_4_VAL_TX,
          DIM.BUSINESS_UNIT_GRP as LKP_BUSINESS_UNIT_GRP
        FROM
          CRPDB01_DEV_SANDBOX.SHMSADM.SHEMS_RPRTNG_GRP_DIM DIM
      ) _lkp_LKPTRANS ON _lkp_LKPTRANS.LKP_LOC_CD = SQ_ODS_SHMS_LOC_ENTTY.LOC_CD
  ) --select * from LKPTRANS;
,EXPTRANS_step1 AS (
    SELECT
      SQ_ODS_SHMS_LOC_ENTTY.*,
      --- EXCLUDE (EDW_LAST_UPDT_TS, EDW_LAST_UPDT_USERID, FLAG, LKP_BUSINESS_UNIT_GRP, LKP_CHECKSUM, LKP_LOC_CD, LKP_RPRTNG_ID, LKP_RPT_GRPLVL_1_VAL_TX, LKP_RPT_GRPLVL_2_VAL_TX, LKP_RPT_GRPLVL_3_VAL_TX, LKP_RPT_GRPLVL_4_VAL_TX, O_ACTIVE_FLAG, O_END_DATE, O_START_DATE, SRC_BUSINESS_UNIT_GRP, SRC_CHECKSUM, SRC_LOC_CD),
      lkp_LKPTRANS.LKP_RPRTNG_ID,
      lkp_LKPTRANS.LKP_RPT_GRPLVL_1_VAL_TX,
      lkp_LKPTRANS.LKP_RPT_GRPLVL_2_VAL_TX,
      lkp_LKPTRANS.LKP_RPT_GRPLVL_3_VAL_TX,
      lkp_LKPTRANS.LKP_RPT_GRPLVL_4_VAL_TX,
      lkp_LKPTRANS.LKP_LOC_CD,
      --lkp_LKPTRANS.SRC_LOC_CD,
      lkp_LKPTRANS.LKP_BUSINESS_UNIT_GRP,
      MD5(
        COALESCE(
          CAST(
            IFF(
              (LKP_RPT_GRPLVL_1_VAL_TX IS NULL),
              ' ',
              LKP_RPT_GRPLVL_1_VAL_TX
            ) AS VARCHAR
          ),
          ''
        ) || COALESCE(
          CAST(
            IFF(
              (LKP_RPT_GRPLVL_2_VAL_TX IS NULL),
              ' ',
              LKP_RPT_GRPLVL_2_VAL_TX
            ) AS VARCHAR
          ),
          ''
        ) || COALESCE(
          CAST(
            IFF(
              (LKP_RPT_GRPLVL_3_VAL_TX IS NULL),
              ' ',
              LKP_RPT_GRPLVL_3_VAL_TX
            ) AS VARCHAR
          ),
          ''
        ) || COALESCE(
          CAST(
            IFF(
              (LKP_RPT_GRPLVL_4_VAL_TX IS NULL),
              ' ',
              LKP_RPT_GRPLVL_4_VAL_TX
            ) AS VARCHAR
          ),
          ''
        )
      ) AS LKP_CHECKSUM,
      MD5(
        COALESCE(
          CAST(
            IFF(
              (RPT_GRPLVL_1_VAL_TX IS NULL),
              ' ',
              RPT_GRPLVL_1_VAL_TX
            ) AS VARCHAR
          ),
          ''
        ) || COALESCE(
          CAST(
            IFF(
              (RPT_GRPLVL_2_VAL_TX IS NULL),
              ' ',
              RPT_GRPLVL_2_VAL_TX
            ) AS VARCHAR
          ),
          ''
        ) || COALESCE(
          CAST(
            IFF(
              (RPT_GRPLVL_3_VAL_TX IS NULL),
              ' ',
              RPT_GRPLVL_3_VAL_TX
            ) AS VARCHAR
          ),
          ''
        ) || COALESCE(
          CAST(
            IFF(
              (RPT_GRPLVL_4_VAL_TX IS NULL),
              ' ',
              RPT_GRPLVL_4_VAL_TX
            ) AS VARCHAR
          ),
          ''
        )
      ) AS SRC_CHECKSUM,
      CASE
        HRCHY_LVL_2_TX
        WHEN 'AEP Corporate' THEN 'Corp/Shared Services'
        WHEN 'AEP External Affairs' THEN 'Corp/Shared Services'
        WHEN 'Chief Administrative Office' THEN 'Corp/Shared Services'
        WHEN 'Chief Info & Tech Officer' THEN 'Corp/Shared Services'
        WHEN 'Energy Supply' THEN 'Corp/Shared Services'
        ELSE HRCHY_LVL_2_TX
      END AS SRC_BUSINESS_UNIT_GRP,
      'Y' AS O_ACTIVE_FLAG,
      CURRENT_TIMESTAMP() AS O_START_DATE,
      TRY_TO_DATE('12-31-9999', 'MM-DD-YYYY') AS O_END_DATE,
      'SHMSUSER' AS EDW_LAST_UPDT_USERID,
      CURRENT_TIMESTAMP() AS EDW_LAST_UPDT_TS
    FROM
      SQ_ODS_SHMS_LOC_ENTTY
      LEFT JOIN (
        SELECT
          DIM.RPRTNG_ID as LKP_RPRTNG_ID,
          DIM.LOC_CD as LKP_LOC_CD,
          DIM.RPT_GRPLVL_1_VAL_TX as LKP_RPT_GRPLVL_1_VAL_TX,
          DIM.RPT_GRPLVL_2_VAL_TX as LKP_RPT_GRPLVL_2_VAL_TX,
          DIM.RPT_GRPLVL_3_VAL_TX as LKP_RPT_GRPLVL_3_VAL_TX,
          DIM.RPT_GRPLVL_4_VAL_TX as LKP_RPT_GRPLVL_4_VAL_TX,
          DIM.BUSINESS_UNIT_GRP as LKP_BUSINESS_UNIT_GRP
        FROM
          CRPDB01_DEV_SANDBOX.SHMSADM.SHEMS_RPRTNG_GRP_DIM DIM
      ) lkp_LKPTRANS ON lkp_LKPTRANS.LKP_LOC_CD = SQ_ODS_SHMS_LOC_ENTTY.LOC_CD
  ) --select * from EXPTRANS_step1;

, EXPTRANS AS (
    SELECT
      EXPTRANS_step1.*,
      IFF(
        (LKP_RPRTNG_ID IS NULL),
        'I',
        IFF(
          NOT ((LKP_RPRTNG_ID IS NULL))
          AND SRC_CHECKSUM <> LKP_CHECKSUM,
          'U',
          NULL
        )
      ) AS FLAG
    FROM
      EXPTRANS_step1
  ) --select Flag from EXPTRANS;
,
RTRTRANS_INSERT AS (
  SELECT
    EXPTRANS.LOC_CD,
    EXPTRANS.RPT_GRPLVL_1_VAL_TX,
    EXPTRANS.RPT_GRPLVL_2_VAL_TX,
    EXPTRANS.RPT_GRPLVL_3_VAL_TX,
    EXPTRANS.RPT_GRPLVL_4_VAL_TX,
    EXPTRANS.HRCHY_LVL_2_TX,
    EXPTRANS.LKP_CHECKSUM,
    EXPTRANS.SRC_CHECKSUM,
    EXPTRANS.SRC_BUSINESS_UNIT_GRP,
    EXPTRANS.FLAG,
    EXPTRANS.O_ACTIVE_FLAG,
    EXPTRANS.O_START_DATE,
    EXPTRANS.O_END_DATE,
    EXPTRANS.EDW_LAST_UPDT_USERID,
    EXPTRANS.EDW_LAST_UPDT_TS
  FROM EXPTRANS
  WHERE FLAG = 'I'
)

,RTRTRANS_INSERT_UPDATE AS (
    SELECT
      EXPTRANS.LOC_CD,
      EXPTRANS.RPT_GRPLVL_1_VAL_TX,
      EXPTRANS.RPT_GRPLVL_2_VAL_TX,
      EXPTRANS.RPT_GRPLVL_3_VAL_TX,
      EXPTRANS.RPT_GRPLVL_4_VAL_TX,
      EXPTRANS.HRCHY_LVL_2_TX,
      EXPTRANS.LKP_CHECKSUM,
      EXPTRANS.SRC_CHECKSUM,
      EXPTRANS.SRC_BUSINESS_UNIT_GRP,
      EXPTRANS.FLAG,
      EXPTRANS.O_ACTIVE_FLAG,
      EXPTRANS.O_START_DATE,
      EXPTRANS.O_END_DATE,
      EXPTRANS.EDW_LAST_UPDT_USERID,
      EXPTRANS.EDW_LAST_UPDT_TS
    FROM
      EXPTRANS
    WHERE
      FLAG = 'U'
  ) ---select * from RTRTRANS_INSERT_UPDATE;
,EXPTRANS1 AS (
    SELECT
      RTRTRANS_INSERT_UPDATE.*
    FROM
      RTRTRANS_INSERT_UPDATE
  ) --select * from EXPTRANS1;

,UPDTRANS2 AS (
    SELECT
      EXPTRANS1.LOC_CD,
      EXPTRANS1.RPT_GRPLVL_1_VAL_TX,
      EXPTRANS1.RPT_GRPLVL_2_VAL_TX,
      EXPTRANS1.RPT_GRPLVL_3_VAL_TX,
      EXPTRANS1.RPT_GRPLVL_4_VAL_TX,
      EXPTRANS1.HRCHY_LVL_2_TX,
      EXPTRANS1.LKP_CHECKSUM,
      EXPTRANS1.SRC_CHECKSUM,
      EXPTRANS1.SRC_BUSINESS_UNIT_GRP,
      EXPTRANS1.FLAG,
      EXPTRANS1.O_ACTIVE_FLAG,
      EXPTRANS1.O_START_DATE,
      EXPTRANS1.O_END_DATE,
      EXPTRANS1.EDW_LAST_UPDT_USERID,
      EXPTRANS1.EDW_LAST_UPDT_TS,
      0 AS DML_FLAG
    FROM
      EXPTRANS1
  ) --select * from UPDTRANS2;
SELECT
  --- LKP_RPRTNG_ID3, 
  COALESCE(
    (
      SELECT
        MAX(RPRTNG_ID)
      FROM
        CRPDB01_DEV_SANDBOX.SHMSADM.SHEMS_RPRTNG_GRP_DIM
    ),
    0
  ) + ROW_NUMBER() OVER (
    ORDER BY
      1
  ) as lkp_RPRTNG_ID,
  O_ACTIVE_FLAG,
  O_START_DATE,
  O_END_DATE,
  EDW_LAST_UPDT_USERID,
  EDW_LAST_UPDT_TS,
  LOC_CD,
  RPT_GRPLVL_1_VAL_TX,
  RPT_GRPLVL_2_VAL_TX,
  RPT_GRPLVL_3_VAL_TX,
  RPT_GRPLVL_4_VAL_TX,
  SRC_BUSINESS_UNIT_GRP
FROM
  UPDTRANS2
WHERE
  DML_FLAG = 0;

--=Flow 2 = == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == =;

-- UPDATE existing records in SHEMS_RPRTNG_GRP_DIM
UPDATE
  CRPDB01_DEV_SANDBOX.SHMSADM.SHEMS_RPRTNG_GRP_DIM tgt
SET
  tgt.ACTIVE_FLAG = src.UPD_ACTIVE_FLAG3,
  tgt.EFFCT_END_DT = src.UPD_END_DATE3,
  tgt.EDW_LAST_UPDT_USER_ID = src.EDW_LAST_UPDT_USERID,
  tgt.EDW_LAST_UPDT_TS = src.EDW_LAST_UPDT_TS
FROM
  (
    WITH SQ_ODS_SHMS_LOC_ENTTY AS (
      SELECT
        A.LOC_CD,
        A.RPT_GRPLVL_1_VAL_TX,
        A.RPT_GRPLVL_2_VAL_TX,
        A.RPT_GRPLVL_3_VAL_TX,
        A.RPT_GRPLVL_4_VAL_TX,
        A.HRCHY_LVL_2_TX
      FROM
        CRPDB01_DEV_SANDBOX.COMMON.ODS_SHMS_LOC_ENTTY_TEST A
      WHERE
        A.RPT_GRPLVL_1_VAL_TX NOT IN('na')
    ) --select * from SQ_ODS_SHMS_LOC_ENTTY;
,LKPTRANS AS (
      SELECT
        SQ_ODS_SHMS_LOC_ENTTY.*,
        -- EXCLUDE (LKP_BUSINESS_UNIT_GRP, LKP_LOC_CD, LKP_RPRTNG_ID, LKP_RPT_GRPLVL_1_VAL_TX, LKP_RPT_GRPLVL_2_VAL_TX, LKP_RPT_GRPLVL_3_VAL_TX, LKP_RPT_GRPLVL_4_VAL_TX, SRC_LOC_CD),
        _lkp_LKPTRANS.LKP_RPRTNG_ID,
        _lkp_LKPTRANS.LKP_RPT_GRPLVL_1_VAL_TX,
        _lkp_LKPTRANS.LKP_RPT_GRPLVL_2_VAL_TX,
        _lkp_LKPTRANS.LKP_RPT_GRPLVL_3_VAL_TX,
        _lkp_LKPTRANS.LKP_RPT_GRPLVL_4_VAL_TX,
        _lkp_LKPTRANS.LKP_LOC_CD,
        SQ_ODS_SHMS_LOC_ENTTY.LOC_CD AS SRC_LOC_CD,
        _lkp_LKPTRANS.LKP_BUSINESS_UNIT_GRP
      FROM
        SQ_ODS_SHMS_LOC_ENTTY
        LEFT JOIN (
          SELECT
            DIM.RPRTNG_ID as LKP_RPRTNG_ID,
            DIM.LOC_CD as LKP_LOC_CD,
            DIM.RPT_GRPLVL_1_VAL_TX as LKP_RPT_GRPLVL_1_VAL_TX,
            DIM.RPT_GRPLVL_2_VAL_TX as LKP_RPT_GRPLVL_2_VAL_TX,
            DIM.RPT_GRPLVL_3_VAL_TX as LKP_RPT_GRPLVL_3_VAL_TX,
            DIM.RPT_GRPLVL_4_VAL_TX as LKP_RPT_GRPLVL_4_VAL_TX,
            DIM.BUSINESS_UNIT_GRP as LKP_BUSINESS_UNIT_GRP
          FROM
            CRPDB01_DEV_SANDBOX.SHMSADM.SHEMS_RPRTNG_GRP_DIM DIM
        ) _lkp_LKPTRANS ON _lkp_LKPTRANS.LKP_LOC_CD = SQ_ODS_SHMS_LOC_ENTTY.LOC_CD
    ) --select * from LKPTRANS;

,EXPTRANS_step1 AS (
      SELECT
        SQ_ODS_SHMS_LOC_ENTTY.*,
        --- EXCLUDE (EDW_LAST_UPDT_TS, EDW_LAST_UPDT_USERID, FLAG, LKP_BUSINESS_UNIT_GRP, LKP_CHECKSUM, LKP_LOC_CD, LKP_RPRTNG_ID, LKP_RPT_GRPLVL_1_VAL_TX, LKP_RPT_GRPLVL_2_VAL_TX, LKP_RPT_GRPLVL_3_VAL_TX, LKP_RPT_GRPLVL_4_VAL_TX, O_ACTIVE_FLAG, O_END_DATE, O_START_DATE, SRC_BUSINESS_UNIT_GRP, SRC_CHECKSUM, SRC_LOC_CD),
        lkp_LKPTRANS.LKP_RPRTNG_ID,
        lkp_LKPTRANS.LKP_RPT_GRPLVL_1_VAL_TX,
        lkp_LKPTRANS.LKP_RPT_GRPLVL_2_VAL_TX,
        lkp_LKPTRANS.LKP_RPT_GRPLVL_3_VAL_TX,
        lkp_LKPTRANS.LKP_RPT_GRPLVL_4_VAL_TX,
        lkp_LKPTRANS.LKP_LOC_CD,
        --lkp_LKPTRANS.SRC_LOC_CD,
        lkp_LKPTRANS.LKP_BUSINESS_UNIT_GRP,
        MD5(
          COALESCE(
            CAST(
              IFF(
                (LKP_RPT_GRPLVL_1_VAL_TX IS NULL),
                ' ',
                LKP_RPT_GRPLVL_1_VAL_TX
              ) AS VARCHAR
            ),
            ''
          ) || COALESCE(
            CAST(
              IFF(
                (LKP_RPT_GRPLVL_2_VAL_TX IS NULL),
                ' ',
                LKP_RPT_GRPLVL_2_VAL_TX
              ) AS VARCHAR
            ),
            ''
          ) || COALESCE(
            CAST(
              IFF(
                (LKP_RPT_GRPLVL_3_VAL_TX IS NULL),
                ' ',
                LKP_RPT_GRPLVL_3_VAL_TX
              ) AS VARCHAR
            ),
            ''
          ) || COALESCE(
            CAST(
              IFF(
                (LKP_RPT_GRPLVL_4_VAL_TX IS NULL),
                ' ',
                LKP_RPT_GRPLVL_4_VAL_TX
              ) AS VARCHAR
            ),
            ''
          )
        ) AS LKP_CHECKSUM,
        MD5(
          COALESCE(
            CAST(
              IFF(
                (RPT_GRPLVL_1_VAL_TX IS NULL),
                ' ',
                RPT_GRPLVL_1_VAL_TX
              ) AS VARCHAR
            ),
            ''
          ) || COALESCE(
            CAST(
              IFF(
                (RPT_GRPLVL_2_VAL_TX IS NULL),
                ' ',
                RPT_GRPLVL_2_VAL_TX
              ) AS VARCHAR
            ),
            ''
          ) || COALESCE(
            CAST(
              IFF(
                (RPT_GRPLVL_3_VAL_TX IS NULL),
                ' ',
                RPT_GRPLVL_3_VAL_TX
              ) AS VARCHAR
            ),
            ''
          ) || COALESCE(
            CAST(
              IFF(
                (RPT_GRPLVL_4_VAL_TX IS NULL),
                ' ',
                RPT_GRPLVL_4_VAL_TX
              ) AS VARCHAR
            ),
            ''
          )
        ) AS SRC_CHECKSUM,
        CASE
          HRCHY_LVL_2_TX
          WHEN 'AEP Corporate' THEN 'Corp/Shared Services'
          WHEN 'AEP External Affairs' THEN 'Corp/Shared Services'
          WHEN 'Chief Administrative Office' THEN 'Corp/Shared Services'
          WHEN 'Chief Info & Tech Officer' THEN 'Corp/Shared Services'
          WHEN 'Energy Supply' THEN 'Corp/Shared Services'
          ELSE HRCHY_LVL_2_TX
        END AS SRC_BUSINESS_UNIT_GRP,
        'Y' AS O_ACTIVE_FLAG,
        CURRENT_TIMESTAMP() AS O_START_DATE,
        TRY_TO_DATE('12-31-9999', 'MM-DD-YYYY') AS O_END_DATE,
        'SHMSUSER' AS EDW_LAST_UPDT_USERID,
        CURRENT_TIMESTAMP() AS EDW_LAST_UPDT_TS
      FROM
        SQ_ODS_SHMS_LOC_ENTTY
        LEFT JOIN (
          SELECT
            DIM.RPRTNG_ID as LKP_RPRTNG_ID,
            DIM.LOC_CD as LKP_LOC_CD,
            DIM.RPT_GRPLVL_1_VAL_TX as LKP_RPT_GRPLVL_1_VAL_TX,
            DIM.RPT_GRPLVL_2_VAL_TX as LKP_RPT_GRPLVL_2_VAL_TX,
            DIM.RPT_GRPLVL_3_VAL_TX as LKP_RPT_GRPLVL_3_VAL_TX,
            DIM.RPT_GRPLVL_4_VAL_TX as LKP_RPT_GRPLVL_4_VAL_TX,
            DIM.BUSINESS_UNIT_GRP as LKP_BUSINESS_UNIT_GRP
          FROM
            CRPDB01_DEV_SANDBOX.SHMSADM.SHEMS_RPRTNG_GRP_DIM DIM
        ) lkp_LKPTRANS ON lkp_LKPTRANS.LKP_LOC_CD = SQ_ODS_SHMS_LOC_ENTTY.LOC_CD
    ) 
    
    --select * from EXPTRANS_step1;
,EXPTRANS AS (
      SELECT
        EXPTRANS_step1.*,
        IFF(
          (LKP_RPRTNG_ID IS NULL),
          'I',
          IFF(
            NOT ((LKP_RPRTNG_ID IS NULL))
            AND SRC_CHECKSUM <> LKP_CHECKSUM,
            'U',
            NULL
          )
        ) AS FLAG
      FROM
        EXPTRANS_step1
    ) ---select * from EXPTRANS;


---select * from RTRTRANS_DEFAULT1;
,RTRTRANS_INSERT_UPDATE AS (
      SELECT
        EXPTRANS.LOC_CD,
        EXPTRANS.RPT_GRPLVL_1_VAL_TX,
        EXPTRANS.RPT_GRPLVL_2_VAL_TX,
        EXPTRANS.RPT_GRPLVL_3_VAL_TX,
        EXPTRANS.RPT_GRPLVL_4_VAL_TX,
        EXPTRANS.HRCHY_LVL_2_TX,
        EXPTRANS.LKP_CHECKSUM,
        EXPTRANS.SRC_CHECKSUM,
        EXPTRANS.SRC_BUSINESS_UNIT_GRP,
        EXPTRANS.FLAG,
        EXPTRANS.O_ACTIVE_FLAG,
        EXPTRANS.O_START_DATE,
        EXPTRANS.O_END_DATE,
        EXPTRANS.EDW_LAST_UPDT_USERID,
        EXPTRANS.EDW_LAST_UPDT_TS
      FROM
        EXPTRANS
      WHERE
        FLAG = 'U'
    ) 
    
    --select * from RTRTRANS_INSERT_UPDATE;

    
,EXPTRANS1 AS (
      SELECT
        RTRTRANS_INSERT_UPDATE.*
      FROM
        RTRTRANS_INSERT_UPDATE
    ) ---select * from EXPTRANS1;
,EXPTRANS2 AS (
      SELECT
        EXPTRANS1.*,
        -- EXCLUDE (UPD_ACTIVE_FLAG3, UPD_END_DATE3),
        'N' AS UPD_ACTIVE_FLAG3,
        CURRENT_TIMESTAMP() AS UPD_END_DATE3
      FROM
        EXPTRANS1
    ) ---select * from EXPTRANS2;
    
,UPDTRANS1 AS (
      SELECT
        EXPTRANS2.LOC_CD,
        EXPTRANS2.RPT_GRPLVL_1_VAL_TX,
        EXPTRANS2.RPT_GRPLVL_2_VAL_TX,
        EXPTRANS2.RPT_GRPLVL_3_VAL_TX,
        EXPTRANS2.RPT_GRPLVL_4_VAL_TX,
        EXPTRANS2.HRCHY_LVL_2_TX,
        EXPTRANS2.LKP_CHECKSUM,
        EXPTRANS2.SRC_CHECKSUM,
        EXPTRANS2.SRC_BUSINESS_UNIT_GRP,
        EXPTRANS2.FLAG,
        EXPTRANS2.O_ACTIVE_FLAG,
        EXPTRANS2.O_START_DATE,
        EXPTRANS2.O_END_DATE,
        EXPTRANS2.EDW_LAST_UPDT_USERID,
        EXPTRANS2.EDW_LAST_UPDT_TS,
        EXPTRANS2.UPD_ACTIVE_FLAG3,
        EXPTRANS2.UPD_END_DATE3,
        COALESCE(
          (
            SELECT
              MAX(RPRTNG_ID)
            FROM
              CRPDB01_DEV_SANDBOX.SHMSADM.SHEMS_RPRTNG_GRP_DIM
          ),
          0
        ) + ROW_NUMBER() OVER (
          ORDER BY
            1
        ) as lkp_RPRTNG_ID,
        1 AS DML_FLAG
      FROM
        EXPTRANS2
    )
    select
      *
    from
      UPDTRANS1
  ) src
WHERE
  tgt.RPRTNG_ID = src.LKP_RPRTNG_ID
  AND src.DML_FLAG = 1;

--== == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == =;

INSERT INTO
  CRPDB01_DEV_SANDBOX.SHMSADM.SHEMS_RPRTNG_GRP_DIM (
    RPT_GRPLVL_3_VAL_TX,
    RPT_GRPLVL_4_VAL_TX,
    LOC_CD,
    RPT_GRPLVL_1_VAL_TX,
    RPT_GRPLVL_2_VAL_TX,
    ACTIVE_FLAG,
    EFFCT_STRT_DT,
    EFFCT_END_DT,
    EDW_LAST_UPDT_USER_ID,
    EDW_LAST_UPDT_TS,
    BUSINESS_UNIT_GRP,
    RPRTNG_ID
  ) 
WITH SQ_ODS_SHMS_LOC_ENTTY AS (
    SELECT
      A.LOC_CD,
      A.RPT_GRPLVL_1_VAL_TX,
      A.RPT_GRPLVL_2_VAL_TX,
      A.RPT_GRPLVL_3_VAL_TX,
      A.RPT_GRPLVL_4_VAL_TX,
      A.HRCHY_LVL_2_TX
    FROM
      CRPDB01_DEV_SANDBOX.COMMON.ODS_SHMS_LOC_ENTTY_TEST A
    WHERE
      A.RPT_GRPLVL_1_VAL_TX NOT IN('na')
  ) --select * from SQ_ODS_SHMS_LOC_ENTTY;
,
  LKPTRANS AS (
    SELECT
      SQ_ODS_SHMS_LOC_ENTTY.*,
      -- EXCLUDE (LKP_BUSINESS_UNIT_GRP, LKP_LOC_CD, LKP_RPRTNG_ID, LKP_RPT_GRPLVL_1_VAL_TX, LKP_RPT_GRPLVL_2_VAL_TX, LKP_RPT_GRPLVL_3_VAL_TX, LKP_RPT_GRPLVL_4_VAL_TX, SRC_LOC_CD),
      _lkp_LKPTRANS.LKP_RPRTNG_ID,
      _lkp_LKPTRANS.LKP_RPT_GRPLVL_1_VAL_TX,
      _lkp_LKPTRANS.LKP_RPT_GRPLVL_2_VAL_TX,
      _lkp_LKPTRANS.LKP_RPT_GRPLVL_3_VAL_TX,
      _lkp_LKPTRANS.LKP_RPT_GRPLVL_4_VAL_TX,
      _lkp_LKPTRANS.LKP_LOC_CD,
      SQ_ODS_SHMS_LOC_ENTTY.LOC_CD AS SRC_LOC_CD,
      _lkp_LKPTRANS.LKP_BUSINESS_UNIT_GRP
    FROM
      SQ_ODS_SHMS_LOC_ENTTY
      LEFT JOIN (
        SELECT
          DIM.RPRTNG_ID as LKP_RPRTNG_ID,
          DIM.LOC_CD as LKP_LOC_CD,
          DIM.RPT_GRPLVL_1_VAL_TX as LKP_RPT_GRPLVL_1_VAL_TX,
          DIM.RPT_GRPLVL_2_VAL_TX as LKP_RPT_GRPLVL_2_VAL_TX,
          DIM.RPT_GRPLVL_3_VAL_TX as LKP_RPT_GRPLVL_3_VAL_TX,
          DIM.RPT_GRPLVL_4_VAL_TX as LKP_RPT_GRPLVL_4_VAL_TX,
          DIM.BUSINESS_UNIT_GRP as LKP_BUSINESS_UNIT_GRP
        FROM
          CRPDB01_DEV_SANDBOX.SHMSADM.SHEMS_RPRTNG_GRP_DIM DIM 
      ) _lkp_LKPTRANS ON _lkp_LKPTRANS.LKP_LOC_CD = SQ_ODS_SHMS_LOC_ENTTY.LOC_CD
  ) --select * from LKPTRANS;
,EXPTRANS_step1 AS (
    SELECT
      SQ_ODS_SHMS_LOC_ENTTY.*,
      --- EXCLUDE (EDW_LAST_UPDT_TS, EDW_LAST_UPDT_USERID, FLAG, LKP_BUSINESS_UNIT_GRP, LKP_CHECKSUM, LKP_LOC_CD, LKP_RPRTNG_ID, LKP_RPT_GRPLVL_1_VAL_TX, LKP_RPT_GRPLVL_2_VAL_TX, LKP_RPT_GRPLVL_3_VAL_TX, LKP_RPT_GRPLVL_4_VAL_TX, O_ACTIVE_FLAG, O_END_DATE, O_START_DATE, SRC_BUSINESS_UNIT_GRP, SRC_CHECKSUM, SRC_LOC_CD),
      lkp_LKPTRANS.LKP_RPRTNG_ID,
      lkp_LKPTRANS.LKP_RPT_GRPLVL_1_VAL_TX,
      lkp_LKPTRANS.LKP_RPT_GRPLVL_2_VAL_TX,
      lkp_LKPTRANS.LKP_RPT_GRPLVL_3_VAL_TX,
      lkp_LKPTRANS.LKP_RPT_GRPLVL_4_VAL_TX,
      lkp_LKPTRANS.LKP_LOC_CD,
      --lkp_LKPTRANS.SRC_LOC_CD,
      lkp_LKPTRANS.LKP_BUSINESS_UNIT_GRP,
      MD5(
        COALESCE(
          CAST(
            IFF(
              (LKP_RPT_GRPLVL_1_VAL_TX IS NULL),
              ' ',
              LKP_RPT_GRPLVL_1_VAL_TX
            ) AS VARCHAR
          ),
          ''
        ) || COALESCE(
          CAST(
            IFF(
              (LKP_RPT_GRPLVL_2_VAL_TX IS NULL),
              ' ',
              LKP_RPT_GRPLVL_2_VAL_TX
            ) AS VARCHAR
          ),
          ''
        ) || COALESCE(
          CAST(
            IFF(
              (LKP_RPT_GRPLVL_3_VAL_TX IS NULL),
              ' ',
              LKP_RPT_GRPLVL_3_VAL_TX
            ) AS VARCHAR
          ),
          ''
        ) || COALESCE(
          CAST(
            IFF(
              (LKP_RPT_GRPLVL_4_VAL_TX IS NULL),
              ' ',
              LKP_RPT_GRPLVL_4_VAL_TX
            ) AS VARCHAR
          ),
          ''
        )
      ) AS LKP_CHECKSUM,
      MD5(
        COALESCE(
          CAST(
            IFF(
              (RPT_GRPLVL_1_VAL_TX IS NULL),
              ' ',
              RPT_GRPLVL_1_VAL_TX
            ) AS VARCHAR
          ),
          ''
        ) || COALESCE(
          CAST(
            IFF(
              (RPT_GRPLVL_2_VAL_TX IS NULL),
              ' ',
              RPT_GRPLVL_2_VAL_TX
            ) AS VARCHAR
          ),
          ''
        ) || COALESCE(
          CAST(
            IFF(
              (RPT_GRPLVL_3_VAL_TX IS NULL),
              ' ',
              RPT_GRPLVL_3_VAL_TX
            ) AS VARCHAR
          ),
          ''
        ) || COALESCE(
          CAST(
            IFF(
              (RPT_GRPLVL_4_VAL_TX IS NULL),
              ' ',
              RPT_GRPLVL_4_VAL_TX
            ) AS VARCHAR
          ),
          ''
        )
      ) AS SRC_CHECKSUM,
      CASE
        HRCHY_LVL_2_TX
        WHEN 'AEP Corporate' THEN 'Corp/Shared Services'
        WHEN 'AEP External Affairs' THEN 'Corp/Shared Services'
        WHEN 'Chief Administrative Office' THEN 'Corp/Shared Services'
        WHEN 'Chief Info & Tech Officer' THEN 'Corp/Shared Services'
        WHEN 'Energy Supply' THEN 'Corp/Shared Services'
        ELSE HRCHY_LVL_2_TX
      END AS SRC_BUSINESS_UNIT_GRP,
      'Y' AS O_ACTIVE_FLAG,
      CURRENT_TIMESTAMP() AS O_START_DATE,
      TRY_TO_DATE('12-31-9999', 'MM-DD-YYYY') AS O_END_DATE,
      'SHMSUSER' AS EDW_LAST_UPDT_USERID,
      CURRENT_TIMESTAMP() AS EDW_LAST_UPDT_TS
    FROM
      SQ_ODS_SHMS_LOC_ENTTY
      LEFT JOIN (
        SELECT
          DIM.RPRTNG_ID as LKP_RPRTNG_ID,
          DIM.LOC_CD as LKP_LOC_CD,
          DIM.RPT_GRPLVL_1_VAL_TX as LKP_RPT_GRPLVL_1_VAL_TX,
          DIM.RPT_GRPLVL_2_VAL_TX as LKP_RPT_GRPLVL_2_VAL_TX,
          DIM.RPT_GRPLVL_3_VAL_TX as LKP_RPT_GRPLVL_3_VAL_TX,
          DIM.RPT_GRPLVL_4_VAL_TX as LKP_RPT_GRPLVL_4_VAL_TX,
          DIM.BUSINESS_UNIT_GRP as LKP_BUSINESS_UNIT_GRP
        FROM
          CRPDB01_DEV_SANDBOX.SHMSADM.SHEMS_RPRTNG_GRP_DIM DIM
      ) lkp_LKPTRANS ON lkp_LKPTRANS.LKP_LOC_CD = SQ_ODS_SHMS_LOC_ENTTY.LOC_CD
  ) ---select * from EXPTRANS_step1;
,EXPTRANS AS (
    SELECT
      EXPTRANS_step1.*,
      IFF(
        (LKP_RPRTNG_ID IS NULL),
        'I',
        IFF(
          NOT ((LKP_RPRTNG_ID IS NULL))
          AND SRC_CHECKSUM <> LKP_CHECKSUM,
          'U',
          NULL
        )
      ) AS FLAG
    FROM
      EXPTRANS_step1
  ) ---select * from EXPTRANS;

,RTRTRANS_INSERT AS (
    SELECT
      EXPTRANS.LOC_CD,
      EXPTRANS.RPT_GRPLVL_1_VAL_TX,
      EXPTRANS.RPT_GRPLVL_2_VAL_TX,
      EXPTRANS.RPT_GRPLVL_3_VAL_TX,
      EXPTRANS.RPT_GRPLVL_4_VAL_TX,
      EXPTRANS.HRCHY_LVL_2_TX,
      EXPTRANS.LKP_CHECKSUM,
      EXPTRANS.SRC_CHECKSUM,
      EXPTRANS.SRC_BUSINESS_UNIT_GRP,
      EXPTRANS.FLAG,
      EXPTRANS.O_ACTIVE_FLAG,
      EXPTRANS.O_START_DATE,
      EXPTRANS.O_END_DATE,
      EXPTRANS.EDW_LAST_UPDT_USERID,
      EXPTRANS.EDW_LAST_UPDT_TS,
      0 AS DML_FLAG
    FROM
      EXPTRANS
    WHERE
      FLAG = 'I'
  ) 
SELECT
  RPT_GRPLVL_3_VAL_TX,
  RPT_GRPLVL_4_VAL_TX,
  --LKP_RPRTNG_ID, 
  LOC_CD,
  RPT_GRPLVL_1_VAL_TX,
  RPT_GRPLVL_2_VAL_TX,
  O_ACTIVE_FLAG,
  O_START_DATE,
  O_END_DATE,
  EDW_LAST_UPDT_USERID,
  EDW_LAST_UPDT_TS,
  SRC_BUSINESS_UNIT_GRP,
  COALESCE(
    (
      SELECT
        MAX(RPRTNG_ID)
      FROM
        CRPDB01_DEV_SANDBOX.SHMSADM.SHEMS_RPRTNG_GRP_DIM
    ),
    0
  ) + ROW_NUMBER() OVER (
    ORDER BY
      1
  ) as lkp_RPRTNG_ID
FROM
  RTRTRANS_INSERT
WHERE
  DML_FLAG = 0;
